#!/bin/bash
# Author: Giacomo Mariani <g.mariani@cineca.it>
# Licensed under BSD licence <http://en.wikipedia.org/wiki/BSD_licenses>
# Last edited: Tue Jun  4 15:46:40 CEST 2013

usage()
{
cat << EOF
usage: $0 [options] -t ticket.list -d directory

This script retrieve a directory and its subdirectories given your tickets file.

OPTIONS:
   -h              Show this message
   -t ticket.list  List of tickets   
   -d directory    Directory to retrieve     
   -v              Verbose
EOF
return 0
}

get_from_ticketfile()
{
echo "Retrieving ${directory} under tickets listed in: ${ticketfile}" ; echo
subdir=${directory%/}
subsubdir=${subdir%/[^/]*}
#echo "subdir: ${subdir}"
#echo "subsubdir: ${subsubdir}"
for i in `cat ${ticketfile}`
do 
    dir=$(echo $i | awk -F"," '{print $1}')
    tts=$(echo $i | awk -F"," '{print $2}')
    if [[ "${dir}" == "${directory}"* ]]
    then
        subtarged=${dir#${subsubdir}}
        pretarged=${subtarged%/[^/]*}
        targed=${pretarged#/}\/
        #echo "subtarget: ${subtarged}"
        #echo "pretarget: ${pretarged}"
        #echo "target: ${targed}"
        if [ ! -d ${targed} ] 
        then
            mkdir ${targed}
        fi
        if [ $VERBOSE ] 
        then 
            echo "dir ${dir} match ${directory}"
            echo "iget -r -t ${tts} ${dir} ${targed}"
            iget -r -t ${tts} ${dir} ${targed}
        else
            iget -r -t ${tts} ${dir} ${targed} 2> /dev/null
        fi
    fi
done

return 0
}

if [ $# -eq "0" ]
then
    echo "Wrong number of arguments." ; echo
    usage
    exit 1
fi

while getopts “t:d:hv” OPTION
do
     case $OPTION in
         t)
             ticketfile=${OPTARG}
             ;; 
         d)
             directory=${OPTARG}
             ;; 
         h)
             usage
             exit 0
             ;;
         v)
             VERBOSE=1
             ;;
         ?)
             usage
             exit 1
             ;;
     esac
done

get_from_ticketfile

exit 0
