API_PLUGIN_NUMBER(HELLO_WORLD_APN,                              1300)
API_PLUGIN_NUMBER(GET_FILE_DESCRIPTOR_INFO_APN,                 20000)
API_PLUGIN_NUMBER(SYNC_WITH_PHYSICAL_OBJECT_APN,                20001)
API_PLUGIN_NUMBER(BATCH_APPLY_METADATA_OPERATIONS_APN,          20002)
