API_PLUGIN_NUMBER(HELLO_WORLD_APN,                              1300)
API_PLUGIN_NUMBER(GET_FILE_DESCRIPTOR_INFO_APN,                 20000)
API_PLUGIN_NUMBER(ATOMIC_APPLY_METADATA_OPERATIONS_APN,         20001)
