TARGET = libosauth.so

SRCS = libosauth.cpp

HEADERS = 

EXTRALIBS = ../../../iRODS/lib/core/obj/eirods_plugin_base.o \
            ../../../iRODS/lib/core/obj/osauth.o \
            ../../../iRODS/lib/api/obj/rcAuthPluginRequest.o


include ../Makefile.base
