/* nedH.h
   Generated by gSOAP 2.7.9l from nedMS_wsdl.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef nedH_H
#define nedH_H
#include "nedStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE___ns3__Revisions
#define SOAP_TYPE___ns3__Revisions (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__Revisions(struct soap*, struct __ns3__Revisions *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__Revisions(struct soap*, const struct __ns3__Revisions *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__Revisions(struct soap*, const struct __ns3__Revisions *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__Revisions(struct soap*, const char*, int, const struct __ns3__Revisions *, const char*);
SOAP_FMAC3 struct __ns3__Revisions * SOAP_FMAC4 soap_get___ns3__Revisions(struct soap*, struct __ns3__Revisions *, const char*, const char*);
SOAP_FMAC3 struct __ns3__Revisions * SOAP_FMAC4 soap_in___ns3__Revisions(struct soap*, const char*, struct __ns3__Revisions *, const char*);

#ifndef SOAP_TYPE___ns3__ObjNearPosn
#define SOAP_TYPE___ns3__ObjNearPosn (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__ObjNearPosn(struct soap*, struct __ns3__ObjNearPosn *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__ObjNearPosn(struct soap*, const struct __ns3__ObjNearPosn *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__ObjNearPosn(struct soap*, const struct __ns3__ObjNearPosn *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__ObjNearPosn(struct soap*, const char*, int, const struct __ns3__ObjNearPosn *, const char*);
SOAP_FMAC3 struct __ns3__ObjNearPosn * SOAP_FMAC4 soap_get___ns3__ObjNearPosn(struct soap*, struct __ns3__ObjNearPosn *, const char*, const char*);
SOAP_FMAC3 struct __ns3__ObjNearPosn * SOAP_FMAC4 soap_in___ns3__ObjNearPosn(struct soap*, const char*, struct __ns3__ObjNearPosn *, const char*);

#ifndef SOAP_TYPE___ns3__ObjNearName
#define SOAP_TYPE___ns3__ObjNearName (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__ObjNearName(struct soap*, struct __ns3__ObjNearName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__ObjNearName(struct soap*, const struct __ns3__ObjNearName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__ObjNearName(struct soap*, const struct __ns3__ObjNearName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__ObjNearName(struct soap*, const char*, int, const struct __ns3__ObjNearName *, const char*);
SOAP_FMAC3 struct __ns3__ObjNearName * SOAP_FMAC4 soap_get___ns3__ObjNearName(struct soap*, struct __ns3__ObjNearName *, const char*, const char*);
SOAP_FMAC3 struct __ns3__ObjNearName * SOAP_FMAC4 soap_in___ns3__ObjNearName(struct soap*, const char*, struct __ns3__ObjNearName *, const char*);

#ifndef SOAP_TYPE___ns3__ObjByName
#define SOAP_TYPE___ns3__ObjByName (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__ObjByName(struct soap*, struct __ns3__ObjByName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__ObjByName(struct soap*, const struct __ns3__ObjByName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__ObjByName(struct soap*, const struct __ns3__ObjByName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__ObjByName(struct soap*, const char*, int, const struct __ns3__ObjByName *, const char*);
SOAP_FMAC3 struct __ns3__ObjByName * SOAP_FMAC4 soap_get___ns3__ObjByName(struct soap*, struct __ns3__ObjByName *, const char*, const char*);
SOAP_FMAC3 struct __ns3__ObjByName * SOAP_FMAC4 soap_in___ns3__ObjByName(struct soap*, const char*, struct __ns3__ObjByName *, const char*);

#ifndef SOAP_TYPE___ns2__Revisions
#define SOAP_TYPE___ns2__Revisions (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__Revisions(struct soap*, struct __ns2__Revisions *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__Revisions(struct soap*, const struct __ns2__Revisions *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__Revisions(struct soap*, const struct __ns2__Revisions *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__Revisions(struct soap*, const char*, int, const struct __ns2__Revisions *, const char*);
SOAP_FMAC3 struct __ns2__Revisions * SOAP_FMAC4 soap_get___ns2__Revisions(struct soap*, struct __ns2__Revisions *, const char*, const char*);
SOAP_FMAC3 struct __ns2__Revisions * SOAP_FMAC4 soap_in___ns2__Revisions(struct soap*, const char*, struct __ns2__Revisions *, const char*);

#ifndef SOAP_TYPE___ns2__ObjNearPosn
#define SOAP_TYPE___ns2__ObjNearPosn (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__ObjNearPosn(struct soap*, struct __ns2__ObjNearPosn *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__ObjNearPosn(struct soap*, const struct __ns2__ObjNearPosn *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__ObjNearPosn(struct soap*, const struct __ns2__ObjNearPosn *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__ObjNearPosn(struct soap*, const char*, int, const struct __ns2__ObjNearPosn *, const char*);
SOAP_FMAC3 struct __ns2__ObjNearPosn * SOAP_FMAC4 soap_get___ns2__ObjNearPosn(struct soap*, struct __ns2__ObjNearPosn *, const char*, const char*);
SOAP_FMAC3 struct __ns2__ObjNearPosn * SOAP_FMAC4 soap_in___ns2__ObjNearPosn(struct soap*, const char*, struct __ns2__ObjNearPosn *, const char*);

#ifndef SOAP_TYPE___ns2__ObjNearName
#define SOAP_TYPE___ns2__ObjNearName (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__ObjNearName(struct soap*, struct __ns2__ObjNearName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__ObjNearName(struct soap*, const struct __ns2__ObjNearName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__ObjNearName(struct soap*, const struct __ns2__ObjNearName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__ObjNearName(struct soap*, const char*, int, const struct __ns2__ObjNearName *, const char*);
SOAP_FMAC3 struct __ns2__ObjNearName * SOAP_FMAC4 soap_get___ns2__ObjNearName(struct soap*, struct __ns2__ObjNearName *, const char*, const char*);
SOAP_FMAC3 struct __ns2__ObjNearName * SOAP_FMAC4 soap_in___ns2__ObjNearName(struct soap*, const char*, struct __ns2__ObjNearName *, const char*);

#ifndef SOAP_TYPE___ns2__ObjByName
#define SOAP_TYPE___ns2__ObjByName (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__ObjByName(struct soap*, struct __ns2__ObjByName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__ObjByName(struct soap*, const struct __ns2__ObjByName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__ObjByName(struct soap*, const struct __ns2__ObjByName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__ObjByName(struct soap*, const char*, int, const struct __ns2__ObjByName *, const char*);
SOAP_FMAC3 struct __ns2__ObjByName * SOAP_FMAC4 soap_get___ns2__ObjByName(struct soap*, struct __ns2__ObjByName *, const char*, const char*);
SOAP_FMAC3 struct __ns2__ObjByName * SOAP_FMAC4 soap_in___ns2__ObjByName(struct soap*, const char*, struct __ns2__ObjByName *, const char*);

#ifndef SOAP_TYPE__ns1__RevisionsResponse
#define SOAP_TYPE__ns1__RevisionsResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__RevisionsResponse(struct soap*, struct _ns1__RevisionsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__RevisionsResponse(struct soap*, const struct _ns1__RevisionsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__RevisionsResponse(struct soap*, const struct _ns1__RevisionsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__RevisionsResponse(struct soap*, const char*, int, const struct _ns1__RevisionsResponse *, const char*);
SOAP_FMAC3 struct _ns1__RevisionsResponse * SOAP_FMAC4 soap_get__ns1__RevisionsResponse(struct soap*, struct _ns1__RevisionsResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__RevisionsResponse * SOAP_FMAC4 soap_in__ns1__RevisionsResponse(struct soap*, const char*, struct _ns1__RevisionsResponse *, const char*);

#ifndef SOAP_TYPE__ns1__Revisions
#define SOAP_TYPE__ns1__Revisions (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__Revisions(struct soap*, struct _ns1__Revisions *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__Revisions(struct soap*, const struct _ns1__Revisions *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__Revisions(struct soap*, const struct _ns1__Revisions *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Revisions(struct soap*, const char*, int, const struct _ns1__Revisions *, const char*);
SOAP_FMAC3 struct _ns1__Revisions * SOAP_FMAC4 soap_get__ns1__Revisions(struct soap*, struct _ns1__Revisions *, const char*, const char*);
SOAP_FMAC3 struct _ns1__Revisions * SOAP_FMAC4 soap_in__ns1__Revisions(struct soap*, const char*, struct _ns1__Revisions *, const char*);

#ifndef SOAP_TYPE__ns1__ObjNearPosnResponse
#define SOAP_TYPE__ns1__ObjNearPosnResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__ObjNearPosnResponse(struct soap*, struct _ns1__ObjNearPosnResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__ObjNearPosnResponse(struct soap*, const struct _ns1__ObjNearPosnResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__ObjNearPosnResponse(struct soap*, const struct _ns1__ObjNearPosnResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ObjNearPosnResponse(struct soap*, const char*, int, const struct _ns1__ObjNearPosnResponse *, const char*);
SOAP_FMAC3 struct _ns1__ObjNearPosnResponse * SOAP_FMAC4 soap_get__ns1__ObjNearPosnResponse(struct soap*, struct _ns1__ObjNearPosnResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjNearPosnResponse * SOAP_FMAC4 soap_in__ns1__ObjNearPosnResponse(struct soap*, const char*, struct _ns1__ObjNearPosnResponse *, const char*);

#ifndef SOAP_TYPE__ns1__ObjNearPosn
#define SOAP_TYPE__ns1__ObjNearPosn (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__ObjNearPosn(struct soap*, struct _ns1__ObjNearPosn *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__ObjNearPosn(struct soap*, const struct _ns1__ObjNearPosn *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__ObjNearPosn(struct soap*, const struct _ns1__ObjNearPosn *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ObjNearPosn(struct soap*, const char*, int, const struct _ns1__ObjNearPosn *, const char*);
SOAP_FMAC3 struct _ns1__ObjNearPosn * SOAP_FMAC4 soap_get__ns1__ObjNearPosn(struct soap*, struct _ns1__ObjNearPosn *, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjNearPosn * SOAP_FMAC4 soap_in__ns1__ObjNearPosn(struct soap*, const char*, struct _ns1__ObjNearPosn *, const char*);

#ifndef SOAP_TYPE__ns1__ObjNearNameResponse
#define SOAP_TYPE__ns1__ObjNearNameResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__ObjNearNameResponse(struct soap*, struct _ns1__ObjNearNameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__ObjNearNameResponse(struct soap*, const struct _ns1__ObjNearNameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__ObjNearNameResponse(struct soap*, const struct _ns1__ObjNearNameResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ObjNearNameResponse(struct soap*, const char*, int, const struct _ns1__ObjNearNameResponse *, const char*);
SOAP_FMAC3 struct _ns1__ObjNearNameResponse * SOAP_FMAC4 soap_get__ns1__ObjNearNameResponse(struct soap*, struct _ns1__ObjNearNameResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjNearNameResponse * SOAP_FMAC4 soap_in__ns1__ObjNearNameResponse(struct soap*, const char*, struct _ns1__ObjNearNameResponse *, const char*);

#ifndef SOAP_TYPE__ns1__ObjNearName
#define SOAP_TYPE__ns1__ObjNearName (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__ObjNearName(struct soap*, struct _ns1__ObjNearName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__ObjNearName(struct soap*, const struct _ns1__ObjNearName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__ObjNearName(struct soap*, const struct _ns1__ObjNearName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ObjNearName(struct soap*, const char*, int, const struct _ns1__ObjNearName *, const char*);
SOAP_FMAC3 struct _ns1__ObjNearName * SOAP_FMAC4 soap_get__ns1__ObjNearName(struct soap*, struct _ns1__ObjNearName *, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjNearName * SOAP_FMAC4 soap_in__ns1__ObjNearName(struct soap*, const char*, struct _ns1__ObjNearName *, const char*);

#ifndef SOAP_TYPE__ns1__ObjByNameResponse
#define SOAP_TYPE__ns1__ObjByNameResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__ObjByNameResponse(struct soap*, struct _ns1__ObjByNameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__ObjByNameResponse(struct soap*, const struct _ns1__ObjByNameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__ObjByNameResponse(struct soap*, const struct _ns1__ObjByNameResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ObjByNameResponse(struct soap*, const char*, int, const struct _ns1__ObjByNameResponse *, const char*);
SOAP_FMAC3 struct _ns1__ObjByNameResponse * SOAP_FMAC4 soap_get__ns1__ObjByNameResponse(struct soap*, struct _ns1__ObjByNameResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjByNameResponse * SOAP_FMAC4 soap_in__ns1__ObjByNameResponse(struct soap*, const char*, struct _ns1__ObjByNameResponse *, const char*);

#ifndef SOAP_TYPE__ns1__ObjByName
#define SOAP_TYPE__ns1__ObjByName (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__ObjByName(struct soap*, struct _ns1__ObjByName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__ObjByName(struct soap*, const struct _ns1__ObjByName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__ObjByName(struct soap*, const struct _ns1__ObjByName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ObjByName(struct soap*, const char*, int, const struct _ns1__ObjByName *, const char*);
SOAP_FMAC3 struct _ns1__ObjByName * SOAP_FMAC4 soap_get__ns1__ObjByName(struct soap*, struct _ns1__ObjByName *, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjByName * SOAP_FMAC4 soap_in__ns1__ObjByName(struct soap*, const char*, struct _ns1__ObjByName *, const char*);

#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ArrayOfString(struct soap*, struct ns1__ArrayOfString *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ArrayOfString(struct soap*, const struct ns1__ArrayOfString *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ArrayOfString(struct soap*, const struct ns1__ArrayOfString *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfString(struct soap*, const char*, int, const struct ns1__ArrayOfString *, const char*);
SOAP_FMAC3 struct ns1__ArrayOfString * SOAP_FMAC4 soap_get_ns1__ArrayOfString(struct soap*, struct ns1__ArrayOfString *, const char*, const char*);
SOAP_FMAC3 struct ns1__ArrayOfString * SOAP_FMAC4 soap_in_ns1__ArrayOfString(struct soap*, const char*, struct ns1__ArrayOfString *, const char*);

#ifndef SOAP_TYPE_ns1__ArrayOfObjInfo
#define SOAP_TYPE_ns1__ArrayOfObjInfo (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ArrayOfObjInfo(struct soap*, struct ns1__ArrayOfObjInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ArrayOfObjInfo(struct soap*, const struct ns1__ArrayOfObjInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ArrayOfObjInfo(struct soap*, const struct ns1__ArrayOfObjInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfObjInfo(struct soap*, const char*, int, const struct ns1__ArrayOfObjInfo *, const char*);
SOAP_FMAC3 struct ns1__ArrayOfObjInfo * SOAP_FMAC4 soap_get_ns1__ArrayOfObjInfo(struct soap*, struct ns1__ArrayOfObjInfo *, const char*, const char*);
SOAP_FMAC3 struct ns1__ArrayOfObjInfo * SOAP_FMAC4 soap_in_ns1__ArrayOfObjInfo(struct soap*, const char*, struct ns1__ArrayOfObjInfo *, const char*);

#ifndef SOAP_TYPE_ns1__MoreData
#define SOAP_TYPE_ns1__MoreData (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__MoreData(struct soap*, struct ns1__MoreData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__MoreData(struct soap*, const struct ns1__MoreData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__MoreData(struct soap*, const struct ns1__MoreData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__MoreData(struct soap*, const char*, int, const struct ns1__MoreData *, const char*);
SOAP_FMAC3 struct ns1__MoreData * SOAP_FMAC4 soap_get_ns1__MoreData(struct soap*, struct ns1__MoreData *, const char*, const char*);
SOAP_FMAC3 struct ns1__MoreData * SOAP_FMAC4 soap_in_ns1__MoreData(struct soap*, const char*, struct ns1__MoreData *, const char*);

#ifndef SOAP_TYPE_ns1__CrossID
#define SOAP_TYPE_ns1__CrossID (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__CrossID(struct soap*, struct ns1__CrossID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__CrossID(struct soap*, const struct ns1__CrossID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__CrossID(struct soap*, const struct ns1__CrossID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__CrossID(struct soap*, const char*, int, const struct ns1__CrossID *, const char*);
SOAP_FMAC3 struct ns1__CrossID * SOAP_FMAC4 soap_get_ns1__CrossID(struct soap*, struct ns1__CrossID *, const char*, const char*);
SOAP_FMAC3 struct ns1__CrossID * SOAP_FMAC4 soap_in_ns1__CrossID(struct soap*, const char*, struct ns1__CrossID *, const char*);

#ifndef SOAP_TYPE_ns1__ArrayOfMoreData
#define SOAP_TYPE_ns1__ArrayOfMoreData (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ArrayOfMoreData(struct soap*, struct ns1__ArrayOfMoreData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ArrayOfMoreData(struct soap*, const struct ns1__ArrayOfMoreData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ArrayOfMoreData(struct soap*, const struct ns1__ArrayOfMoreData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfMoreData(struct soap*, const char*, int, const struct ns1__ArrayOfMoreData *, const char*);
SOAP_FMAC3 struct ns1__ArrayOfMoreData * SOAP_FMAC4 soap_get_ns1__ArrayOfMoreData(struct soap*, struct ns1__ArrayOfMoreData *, const char*, const char*);
SOAP_FMAC3 struct ns1__ArrayOfMoreData * SOAP_FMAC4 soap_in_ns1__ArrayOfMoreData(struct soap*, const char*, struct ns1__ArrayOfMoreData *, const char*);

#ifndef SOAP_TYPE_ns1__ArrayOfCrossID
#define SOAP_TYPE_ns1__ArrayOfCrossID (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ArrayOfCrossID(struct soap*, struct ns1__ArrayOfCrossID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ArrayOfCrossID(struct soap*, const struct ns1__ArrayOfCrossID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ArrayOfCrossID(struct soap*, const struct ns1__ArrayOfCrossID *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfCrossID(struct soap*, const char*, int, const struct ns1__ArrayOfCrossID *, const char*);
SOAP_FMAC3 struct ns1__ArrayOfCrossID * SOAP_FMAC4 soap_get_ns1__ArrayOfCrossID(struct soap*, struct ns1__ArrayOfCrossID *, const char*, const char*);
SOAP_FMAC3 struct ns1__ArrayOfCrossID * SOAP_FMAC4 soap_in_ns1__ArrayOfCrossID(struct soap*, const char*, struct ns1__ArrayOfCrossID *, const char*);

#ifndef SOAP_TYPE_ns1__ObjInfo
#define SOAP_TYPE_ns1__ObjInfo (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ObjInfo(struct soap*, struct ns1__ObjInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ObjInfo(struct soap*, const struct ns1__ObjInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ObjInfo(struct soap*, const struct ns1__ObjInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ObjInfo(struct soap*, const char*, int, const struct ns1__ObjInfo *, const char*);
SOAP_FMAC3 struct ns1__ObjInfo * SOAP_FMAC4 soap_get_ns1__ObjInfo(struct soap*, struct ns1__ObjInfo *, const char*, const char*);
SOAP_FMAC3 struct ns1__ObjInfo * SOAP_FMAC4 soap_in_ns1__ObjInfo(struct soap*, const char*, struct ns1__ObjInfo *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__RevisionsResponse
#define SOAP_TYPE_PointerTo_ns1__RevisionsResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__RevisionsResponse(struct soap*, struct _ns1__RevisionsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__RevisionsResponse(struct soap*, struct _ns1__RevisionsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__RevisionsResponse(struct soap*, const char *, int, struct _ns1__RevisionsResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__RevisionsResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__RevisionsResponse(struct soap*, struct _ns1__RevisionsResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__RevisionsResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__RevisionsResponse(struct soap*, const char*, struct _ns1__RevisionsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__Revisions
#define SOAP_TYPE_PointerTo_ns1__Revisions (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Revisions(struct soap*, struct _ns1__Revisions *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Revisions(struct soap*, struct _ns1__Revisions *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Revisions(struct soap*, const char *, int, struct _ns1__Revisions *const*, const char *);
SOAP_FMAC3 struct _ns1__Revisions ** SOAP_FMAC4 soap_get_PointerTo_ns1__Revisions(struct soap*, struct _ns1__Revisions **, const char*, const char*);
SOAP_FMAC3 struct _ns1__Revisions ** SOAP_FMAC4 soap_in_PointerTo_ns1__Revisions(struct soap*, const char*, struct _ns1__Revisions **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ObjNearPosnResponse
#define SOAP_TYPE_PointerTo_ns1__ObjNearPosnResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ObjNearPosnResponse(struct soap*, struct _ns1__ObjNearPosnResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ObjNearPosnResponse(struct soap*, struct _ns1__ObjNearPosnResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ObjNearPosnResponse(struct soap*, const char *, int, struct _ns1__ObjNearPosnResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__ObjNearPosnResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__ObjNearPosnResponse(struct soap*, struct _ns1__ObjNearPosnResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjNearPosnResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__ObjNearPosnResponse(struct soap*, const char*, struct _ns1__ObjNearPosnResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ObjNearPosn
#define SOAP_TYPE_PointerTo_ns1__ObjNearPosn (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ObjNearPosn(struct soap*, struct _ns1__ObjNearPosn *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ObjNearPosn(struct soap*, struct _ns1__ObjNearPosn *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ObjNearPosn(struct soap*, const char *, int, struct _ns1__ObjNearPosn *const*, const char *);
SOAP_FMAC3 struct _ns1__ObjNearPosn ** SOAP_FMAC4 soap_get_PointerTo_ns1__ObjNearPosn(struct soap*, struct _ns1__ObjNearPosn **, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjNearPosn ** SOAP_FMAC4 soap_in_PointerTo_ns1__ObjNearPosn(struct soap*, const char*, struct _ns1__ObjNearPosn **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ObjNearNameResponse
#define SOAP_TYPE_PointerTo_ns1__ObjNearNameResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ObjNearNameResponse(struct soap*, struct _ns1__ObjNearNameResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ObjNearNameResponse(struct soap*, struct _ns1__ObjNearNameResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ObjNearNameResponse(struct soap*, const char *, int, struct _ns1__ObjNearNameResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__ObjNearNameResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__ObjNearNameResponse(struct soap*, struct _ns1__ObjNearNameResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjNearNameResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__ObjNearNameResponse(struct soap*, const char*, struct _ns1__ObjNearNameResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ObjNearName
#define SOAP_TYPE_PointerTo_ns1__ObjNearName (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ObjNearName(struct soap*, struct _ns1__ObjNearName *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ObjNearName(struct soap*, struct _ns1__ObjNearName *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ObjNearName(struct soap*, const char *, int, struct _ns1__ObjNearName *const*, const char *);
SOAP_FMAC3 struct _ns1__ObjNearName ** SOAP_FMAC4 soap_get_PointerTo_ns1__ObjNearName(struct soap*, struct _ns1__ObjNearName **, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjNearName ** SOAP_FMAC4 soap_in_PointerTo_ns1__ObjNearName(struct soap*, const char*, struct _ns1__ObjNearName **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ObjByNameResponse
#define SOAP_TYPE_PointerTo_ns1__ObjByNameResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ObjByNameResponse(struct soap*, struct _ns1__ObjByNameResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ObjByNameResponse(struct soap*, struct _ns1__ObjByNameResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ObjByNameResponse(struct soap*, const char *, int, struct _ns1__ObjByNameResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__ObjByNameResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__ObjByNameResponse(struct soap*, struct _ns1__ObjByNameResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjByNameResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__ObjByNameResponse(struct soap*, const char*, struct _ns1__ObjByNameResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ObjByName
#define SOAP_TYPE_PointerTo_ns1__ObjByName (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ObjByName(struct soap*, struct _ns1__ObjByName *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ObjByName(struct soap*, struct _ns1__ObjByName *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ObjByName(struct soap*, const char *, int, struct _ns1__ObjByName *const*, const char *);
SOAP_FMAC3 struct _ns1__ObjByName ** SOAP_FMAC4 soap_get_PointerTo_ns1__ObjByName(struct soap*, struct _ns1__ObjByName **, const char*, const char*);
SOAP_FMAC3 struct _ns1__ObjByName ** SOAP_FMAC4 soap_in_PointerTo_ns1__ObjByName(struct soap*, const char*, struct _ns1__ObjByName **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfString
#define SOAP_TYPE_PointerTons1__ArrayOfString (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfString(struct soap*, struct ns1__ArrayOfString *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfString(struct soap*, struct ns1__ArrayOfString *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfString(struct soap*, const char *, int, struct ns1__ArrayOfString *const*, const char *);
SOAP_FMAC3 struct ns1__ArrayOfString ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfString(struct soap*, struct ns1__ArrayOfString **, const char*, const char*);
SOAP_FMAC3 struct ns1__ArrayOfString ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfString(struct soap*, const char*, struct ns1__ArrayOfString **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfObjInfo
#define SOAP_TYPE_PointerTons1__ArrayOfObjInfo (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfObjInfo(struct soap*, struct ns1__ArrayOfObjInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfObjInfo(struct soap*, struct ns1__ArrayOfObjInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfObjInfo(struct soap*, const char *, int, struct ns1__ArrayOfObjInfo *const*, const char *);
SOAP_FMAC3 struct ns1__ArrayOfObjInfo ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfObjInfo(struct soap*, struct ns1__ArrayOfObjInfo **, const char*, const char*);
SOAP_FMAC3 struct ns1__ArrayOfObjInfo ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfObjInfo(struct soap*, const char*, struct ns1__ArrayOfObjInfo **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__ObjInfo
#define SOAP_TYPE_PointerTons1__ObjInfo (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ObjInfo(struct soap*, struct ns1__ObjInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ObjInfo(struct soap*, struct ns1__ObjInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ObjInfo(struct soap*, const char *, int, struct ns1__ObjInfo *const*, const char *);
SOAP_FMAC3 struct ns1__ObjInfo ** SOAP_FMAC4 soap_get_PointerTons1__ObjInfo(struct soap*, struct ns1__ObjInfo **, const char*, const char*);
SOAP_FMAC3 struct ns1__ObjInfo ** SOAP_FMAC4 soap_in_PointerTons1__ObjInfo(struct soap*, const char*, struct ns1__ObjInfo **, const char*);

#ifndef SOAP_TYPE_PointerTons1__MoreData
#define SOAP_TYPE_PointerTons1__MoreData (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__MoreData(struct soap*, struct ns1__MoreData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__MoreData(struct soap*, struct ns1__MoreData *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__MoreData(struct soap*, const char *, int, struct ns1__MoreData *const*, const char *);
SOAP_FMAC3 struct ns1__MoreData ** SOAP_FMAC4 soap_get_PointerTons1__MoreData(struct soap*, struct ns1__MoreData **, const char*, const char*);
SOAP_FMAC3 struct ns1__MoreData ** SOAP_FMAC4 soap_in_PointerTons1__MoreData(struct soap*, const char*, struct ns1__MoreData **, const char*);

#ifndef SOAP_TYPE_PointerTons1__CrossID
#define SOAP_TYPE_PointerTons1__CrossID (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__CrossID(struct soap*, struct ns1__CrossID *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__CrossID(struct soap*, struct ns1__CrossID *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__CrossID(struct soap*, const char *, int, struct ns1__CrossID *const*, const char *);
SOAP_FMAC3 struct ns1__CrossID ** SOAP_FMAC4 soap_get_PointerTons1__CrossID(struct soap*, struct ns1__CrossID **, const char*, const char*);
SOAP_FMAC3 struct ns1__CrossID ** SOAP_FMAC4 soap_in_PointerTons1__CrossID(struct soap*, const char*, struct ns1__CrossID **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfMoreData
#define SOAP_TYPE_PointerTons1__ArrayOfMoreData (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfMoreData(struct soap*, struct ns1__ArrayOfMoreData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfMoreData(struct soap*, struct ns1__ArrayOfMoreData *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfMoreData(struct soap*, const char *, int, struct ns1__ArrayOfMoreData *const*, const char *);
SOAP_FMAC3 struct ns1__ArrayOfMoreData ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfMoreData(struct soap*, struct ns1__ArrayOfMoreData **, const char*, const char*);
SOAP_FMAC3 struct ns1__ArrayOfMoreData ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfMoreData(struct soap*, const char*, struct ns1__ArrayOfMoreData **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfCrossID
#define SOAP_TYPE_PointerTons1__ArrayOfCrossID (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfCrossID(struct soap*, struct ns1__ArrayOfCrossID *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfCrossID(struct soap*, struct ns1__ArrayOfCrossID *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfCrossID(struct soap*, const char *, int, struct ns1__ArrayOfCrossID *const*, const char *);
SOAP_FMAC3 struct ns1__ArrayOfCrossID ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfCrossID(struct soap*, struct ns1__ArrayOfCrossID **, const char*, const char*);
SOAP_FMAC3 struct ns1__ArrayOfCrossID ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfCrossID(struct soap*, const char*, struct ns1__ArrayOfCrossID **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of nedH.h */
