/* sdssImgCutoutClient.c
   Generated by gSOAP 2.7.9l from sdssImgCutoutMS_wsdl.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "sdssImgCutoutH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) sdssImgCutoutClient.c ver 2.7.9l 2008-01-25 19:19:35 GMT")

#ifdef RAJAOUT
SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__Revisions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__Revisions *ns1__Revisions, struct _ns1__RevisionsResponse *ns1__RevisionsResponse)
{	struct __ns2__Revisions soap_tmp___ns2__Revisions;
	if (!soap_endpoint)
		soap_endpoint = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx";
	if (!soap_action)
		soap_action = "http://skyserver.sdss.org/Revisions";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__Revisions.ns1__Revisions = ns1__Revisions;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__Revisions(soap, &soap_tmp___ns2__Revisions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__Revisions(soap, &soap_tmp___ns2__Revisions, "-ns2:Revisions", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__Revisions(soap, &soap_tmp___ns2__Revisions, "-ns2:Revisions", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__RevisionsResponse(soap, ns1__RevisionsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__RevisionsResponse(soap, ns1__RevisionsResponse, "ns1:RevisionsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
	    return soap_recv_fault(soap,1);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif /* RAJAOUT */
SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__GetJpeg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetJpeg *ns1__GetJpeg, struct _ns1__GetJpegResponse *ns1__GetJpegResponse)
{	struct __ns2__GetJpeg soap_tmp___ns2__GetJpeg;
	if (!soap_endpoint)
		soap_endpoint = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx";
	if (!soap_action)
		soap_action = "http://skyserver.sdss.org/GetJpeg";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetJpeg.ns1__GetJpeg = ns1__GetJpeg;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetJpeg(soap, &soap_tmp___ns2__GetJpeg);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetJpeg(soap, &soap_tmp___ns2__GetJpeg, "-ns2:GetJpeg", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetJpeg(soap, &soap_tmp___ns2__GetJpeg, "-ns2:GetJpeg", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__GetJpegResponse(soap, ns1__GetJpegResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetJpegResponse(soap, ns1__GetJpegResponse, "ns1:GetJpegResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
	    return soap_recv_fault(soap,1);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__GetJpegQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetJpegQuery *ns1__GetJpegQuery, struct _ns1__GetJpegQueryResponse *ns1__GetJpegQueryResponse)
{	struct __ns2__GetJpegQuery soap_tmp___ns2__GetJpegQuery;
	if (!soap_endpoint)
		soap_endpoint = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx";
	if (!soap_action)
		soap_action = "http://skyserver.sdss.org/GetJpegQuery";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetJpegQuery.ns1__GetJpegQuery = ns1__GetJpegQuery;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetJpegQuery(soap, &soap_tmp___ns2__GetJpegQuery);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetJpegQuery(soap, &soap_tmp___ns2__GetJpegQuery, "-ns2:GetJpegQuery", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetJpegQuery(soap, &soap_tmp___ns2__GetJpegQuery, "-ns2:GetJpegQuery", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__GetJpegQueryResponse(soap, ns1__GetJpegQueryResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetJpegQueryResponse(soap, ns1__GetJpegQueryResponse, "ns1:GetJpegQueryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
	    return soap_recv_fault(soap,1);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__DimeJpeg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__DimeJpeg *ns1__DimeJpeg, struct _ns1__DimeJpegResponse *ns1__DimeJpegResponse)
{	struct __ns2__DimeJpeg soap_tmp___ns2__DimeJpeg;
	if (!soap_endpoint)
		soap_endpoint = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx";
	if (!soap_action)
		soap_action = "http://skyserver.sdss.org/DimeJpeg";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__DimeJpeg.ns1__DimeJpeg = ns1__DimeJpeg;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__DimeJpeg(soap, &soap_tmp___ns2__DimeJpeg);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__DimeJpeg(soap, &soap_tmp___ns2__DimeJpeg, "-ns2:DimeJpeg", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__DimeJpeg(soap, &soap_tmp___ns2__DimeJpeg, "-ns2:DimeJpeg", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__DimeJpegResponse(soap, ns1__DimeJpegResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__DimeJpegResponse(soap, ns1__DimeJpegResponse, "ns1:DimeJpegResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
	    return soap_recv_fault(soap,1);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef RAJAOUT

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__Revisions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__Revisions *ns1__Revisions, struct _ns1__RevisionsResponse *ns1__RevisionsResponse)
{	struct __ns3__Revisions soap_tmp___ns3__Revisions;
	if (!soap_endpoint)
		soap_endpoint = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx";
	if (!soap_action)
		soap_action = "http://skyserver.sdss.org/Revisions";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__Revisions.ns1__Revisions = ns1__Revisions;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__Revisions(soap, &soap_tmp___ns3__Revisions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__Revisions(soap, &soap_tmp___ns3__Revisions, "-ns3:Revisions", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__Revisions(soap, &soap_tmp___ns3__Revisions, "-ns3:Revisions", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__RevisionsResponse(soap, ns1__RevisionsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__RevisionsResponse(soap, ns1__RevisionsResponse, "ns1:RevisionsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
	    return soap_recv_fault(soap,1);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif /* RAJAOUT */

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__GetJpeg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetJpeg *ns1__GetJpeg, struct _ns1__GetJpegResponse *ns1__GetJpegResponse)
{	struct __ns3__GetJpeg soap_tmp___ns3__GetJpeg;
	if (!soap_endpoint)
		soap_endpoint = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx";
	if (!soap_action)
		soap_action = "http://skyserver.sdss.org/GetJpeg";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__GetJpeg.ns1__GetJpeg = ns1__GetJpeg;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__GetJpeg(soap, &soap_tmp___ns3__GetJpeg);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__GetJpeg(soap, &soap_tmp___ns3__GetJpeg, "-ns3:GetJpeg", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__GetJpeg(soap, &soap_tmp___ns3__GetJpeg, "-ns3:GetJpeg", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__GetJpegResponse(soap, ns1__GetJpegResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetJpegResponse(soap, ns1__GetJpegResponse, "ns1:GetJpegResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
	    return soap_recv_fault(soap,1);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__GetJpegQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetJpegQuery *ns1__GetJpegQuery, struct _ns1__GetJpegQueryResponse *ns1__GetJpegQueryResponse)
{	struct __ns3__GetJpegQuery soap_tmp___ns3__GetJpegQuery;
	if (!soap_endpoint)
		soap_endpoint = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx";
	if (!soap_action)
		soap_action = "http://skyserver.sdss.org/GetJpegQuery";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__GetJpegQuery.ns1__GetJpegQuery = ns1__GetJpegQuery;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__GetJpegQuery(soap, &soap_tmp___ns3__GetJpegQuery);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__GetJpegQuery(soap, &soap_tmp___ns3__GetJpegQuery, "-ns3:GetJpegQuery", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__GetJpegQuery(soap, &soap_tmp___ns3__GetJpegQuery, "-ns3:GetJpegQuery", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__GetJpegQueryResponse(soap, ns1__GetJpegQueryResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetJpegQueryResponse(soap, ns1__GetJpegQueryResponse, "ns1:GetJpegQueryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
	    return soap_recv_fault(soap,1);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__DimeJpeg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__DimeJpeg *ns1__DimeJpeg, struct _ns1__DimeJpegResponse *ns1__DimeJpegResponse)
{	struct __ns3__DimeJpeg soap_tmp___ns3__DimeJpeg;
	if (!soap_endpoint)
		soap_endpoint = "http://casjobs.sdss.org/ImgCutoutDR5/ImgCutout.asmx";
	if (!soap_action)
		soap_action = "http://skyserver.sdss.org/DimeJpeg";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__DimeJpeg.ns1__DimeJpeg = ns1__DimeJpeg;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__DimeJpeg(soap, &soap_tmp___ns3__DimeJpeg);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__DimeJpeg(soap, &soap_tmp___ns3__DimeJpeg, "-ns3:DimeJpeg", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__DimeJpeg(soap, &soap_tmp___ns3__DimeJpeg, "-ns3:DimeJpeg", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__DimeJpegResponse(soap, ns1__DimeJpegResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__DimeJpegResponse(soap, ns1__DimeJpegResponse, "ns1:DimeJpegResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
	    return soap_recv_fault(soap,1);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of sdssImgCutoutClient.c */
