/* sdssImgCutoutStub.h
   Generated by gSOAP 2.7.9l from sdssImgCutoutMS_wsdl.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef sdssImgCutoutStub_H
#define sdssImgCutoutStub_H
#ifndef WITH_NONAMESPACES
#define WITH_NONAMESPACES
#endif
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (6)
/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (10)
/* ns1:ArrayOfString */
struct ns1__ArrayOfString
{
	int __sizestring;	/* sequence of elements <string> */
	char **string;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__Revisions
#define SOAP_TYPE__ns1__Revisions (12)
/* ns1:Revisions */
struct _ns1__Revisions
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__RevisionsResponse
#define SOAP_TYPE__ns1__RevisionsResponse (13)
/* ns1:RevisionsResponse */
struct _ns1__RevisionsResponse
{
	struct ns1__ArrayOfString *RevisionsResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ArrayOfString */
};
#endif

#ifndef SOAP_TYPE__ns1__GetJpeg
#define SOAP_TYPE__ns1__GetJpeg (15)
/* ns1:GetJpeg */
struct _ns1__GetJpeg
{
	double ra_USCORE;	/* required element of type xsd:double */
	double dec_USCORE;	/* required element of type xsd:double */
	double scale_USCORE;	/* required element of type xsd:double */
	int width_USCORE;	/* required element of type xsd:int */
	int height_USCORE;	/* required element of type xsd:int */
	char *opt_USCORE;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetJpegResponse
#define SOAP_TYPE__ns1__GetJpegResponse (17)
/* ns1:GetJpegResponse */
struct _ns1__GetJpegResponse
{
	struct xsd__base64Binary *GetJpegResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE__ns1__GetJpegQuery
#define SOAP_TYPE__ns1__GetJpegQuery (19)
/* ns1:GetJpegQuery */
struct _ns1__GetJpegQuery
{
	double ra_USCORE;	/* required element of type xsd:double */
	double dec_USCORE;	/* required element of type xsd:double */
	double scale_USCORE;	/* required element of type xsd:double */
	int width_USCORE;	/* required element of type xsd:int */
	int height_USCORE;	/* required element of type xsd:int */
	char *opt_USCORE;	/* optional element of type xsd:string */
	char *query_USCORE;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetJpegQueryResponse
#define SOAP_TYPE__ns1__GetJpegQueryResponse (20)
/* ns1:GetJpegQueryResponse */
struct _ns1__GetJpegQueryResponse
{
	struct xsd__base64Binary *GetJpegQueryResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE__ns1__DimeJpeg
#define SOAP_TYPE__ns1__DimeJpeg (21)
/* ns1:DimeJpeg */
struct _ns1__DimeJpeg
{
	double ra_USCORE;	/* required element of type xsd:double */
	double dec_USCORE;	/* required element of type xsd:double */
	double scale_USCORE;	/* required element of type xsd:double */
	int width_USCORE;	/* required element of type xsd:int */
	int height_USCORE;	/* required element of type xsd:int */
	char *opt_USCORE;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__DimeJpegResponse
#define SOAP_TYPE__ns1__DimeJpegResponse (22)
/* ns1:DimeJpegResponse */
struct _ns1__DimeJpegResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE___ns2__Revisions
#define SOAP_TYPE___ns2__Revisions (26)
/* Operation wrapper: */
struct __ns2__Revisions
{
	struct _ns1__Revisions *ns1__Revisions;	/* optional element of type ns1:Revisions */
};
#endif

#ifndef SOAP_TYPE___ns2__GetJpeg
#define SOAP_TYPE___ns2__GetJpeg (30)
/* Operation wrapper: */
struct __ns2__GetJpeg
{
	struct _ns1__GetJpeg *ns1__GetJpeg;	/* optional element of type ns1:GetJpeg */
};
#endif

#ifndef SOAP_TYPE___ns2__GetJpegQuery
#define SOAP_TYPE___ns2__GetJpegQuery (34)
/* Operation wrapper: */
struct __ns2__GetJpegQuery
{
	struct _ns1__GetJpegQuery *ns1__GetJpegQuery;	/* optional element of type ns1:GetJpegQuery */
};
#endif

#ifndef SOAP_TYPE___ns2__DimeJpeg
#define SOAP_TYPE___ns2__DimeJpeg (38)
/* Operation wrapper: */
struct __ns2__DimeJpeg
{
	struct _ns1__DimeJpeg *ns1__DimeJpeg;	/* optional element of type ns1:DimeJpeg */
};
#endif

#ifndef SOAP_TYPE___ns3__Revisions
#define SOAP_TYPE___ns3__Revisions (40)
/* Operation wrapper: */
struct __ns3__Revisions
{
	struct _ns1__Revisions *ns1__Revisions;	/* optional element of type ns1:Revisions */
};
#endif

#ifndef SOAP_TYPE___ns3__GetJpeg
#define SOAP_TYPE___ns3__GetJpeg (42)
/* Operation wrapper: */
struct __ns3__GetJpeg
{
	struct _ns1__GetJpeg *ns1__GetJpeg;	/* optional element of type ns1:GetJpeg */
};
#endif

#ifndef SOAP_TYPE___ns3__GetJpegQuery
#define SOAP_TYPE___ns3__GetJpegQuery (44)
/* Operation wrapper: */
struct __ns3__GetJpegQuery
{
	struct _ns1__GetJpegQuery *ns1__GetJpegQuery;	/* optional element of type ns1:GetJpegQuery */
};
#endif

#ifndef SOAP_TYPE___ns3__DimeJpeg
#define SOAP_TYPE___ns3__DimeJpeg (46)
/* Operation wrapper: */
struct __ns3__DimeJpeg
{
	struct _ns1__DimeJpeg *ns1__DimeJpeg;	/* optional element of type ns1:DimeJpeg */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (47)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (48)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (50)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (53)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (54)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__Revisions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__Revisions *ns1__Revisions, struct _ns1__RevisionsResponse *ns1__RevisionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__GetJpeg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetJpeg *ns1__GetJpeg, struct _ns1__GetJpegResponse *ns1__GetJpegResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__GetJpegQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetJpegQuery *ns1__GetJpegQuery, struct _ns1__GetJpegQueryResponse *ns1__GetJpegQueryResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__DimeJpeg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__DimeJpeg *ns1__DimeJpeg, struct _ns1__DimeJpegResponse *ns1__DimeJpegResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__Revisions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__Revisions *ns1__Revisions, struct _ns1__RevisionsResponse *ns1__RevisionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__GetJpeg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetJpeg *ns1__GetJpeg, struct _ns1__GetJpegResponse *ns1__GetJpegResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__GetJpegQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetJpegQuery *ns1__GetJpegQuery, struct _ns1__GetJpegQueryResponse *ns1__GetJpegQueryResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__DimeJpeg(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__DimeJpeg *ns1__DimeJpeg, struct _ns1__DimeJpegResponse *ns1__DimeJpegResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of sdssImgCutoutStub.h */
