#ifndef IRODS_GENQUERY2_SCANNER_HPP
#define IRODS_GENQUERY2_SCANNER_HPP

#include "parser.hpp" // Generated by Bison.

#ifndef yyFlexLexerOnce
#  include <FlexLexer.h>
#endif // yyFlexLexerOnce

namespace irods::experimental::genquery2
{
    class driver;

    class scanner : public yyFlexLexer
    {
      public:
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverloaded-virtual"
        auto yylex(driver& _driver) -> yy::parser::symbol_type;
#pragma GCC diagnostic pop
    }; // class scanner
} // namespace irods::experimental::genquery2

#endif // IRODS_GENQUERY2_SCANNER_HPP
