#!/bin/sh
#
# Control the iRODS servers.
#
# Usage is:
#       irodsctl [args] [options]
#
# Type 'irodsctl --help' for a list of options.
#
# This shell script runs the 'irods_control' Python script.
#
IRODS_HOME=$(dirname $0)
python3 $IRODS_HOME/scripts/irods_control.py $*
exit $?
