// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "webdisp_explorer.h"

/////////////////////////////////////////////////////////////////////////////
// CWebdisp_explorer

IMPLEMENT_DYNCREATE(CWebdisp_explorer, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CWebdisp_explorer properties

/////////////////////////////////////////////////////////////////////////////
// CWebdisp_explorer operations
