/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* apiPackTable.h - This file may be generated by a program or script
 */

#ifndef API_PACK_TABLE_HPP
#define API_PACK_TABLE_HPP

#include "rods.hpp"
#include "packStruct.hpp"
#include "rodsPackInstruct.hpp"

/* need to include a header for for each API */
#include "apiHeaderAll.hpp"

packInstruct_t MiscSvrInfo_PIG = MiscSvrInfo_PI;

static void noop(void*) {};

packInstructArray_t api_pack_table_init[] = {
    {"DataObjInp_PI", DataObjInp_PI, noop},
    {"OpenedDataObjInp_PI", OpenedDataObjInp_PI, noop},
    {"DataCopyInp_PI", DataCopyInp_PI, noop},
    {"DataObjCopyInp_PI", DataObjCopyInp_PI, noop},
    {"fileOpenInp_PI", fileOpenInp_PI, noop},
    {"fileChksumInp_PI", fileChksumInp_PI, noop},
    {"fileChksumOut_PI", fileChksumOut_PI, noop},
    {"fileLseekInp_PI", fileLseekInp_PI, noop},
    {"fileLseekOut_PI", fileLseekOut_PI, noop},
    {"fileStatInp_PI", fileStatInp_PI, noop},
    {"fileUnlinkInp_PI", fileUnlinkInp_PI, noop},
    {"fileReadInp_PI", fileReadInp_PI, noop},
    {"fileChmodInp_PI", fileChmodInp_PI, noop},
    {"fileCloseInp_PI", fileCloseInp_PI, noop},
    {"fileGetFsFreeSpaceInp_PI", fileGetFsFreeSpaceInp_PI, noop},
    {"fileGetFsFreeSpaceOut_PI", fileGetFsFreeSpaceOut_PI, noop},
    {"fileMkdirInp_PI", fileMkdirInp_PI, noop},
    {"fileOpendirInp_PI", fileOpendirInp_PI, noop},
    {"fileReaddirInp_PI", fileReaddirInp_PI, noop},
    {"fileRenameInp_PI", fileRenameInp_PI, noop},
    {"fileRmdirInp_PI", fileRmdirInp_PI, noop},
    {"fileWriteInp_PI", fileWriteInp_PI, noop},
    {"fileClosedirInp_PI", fileClosedirInp_PI, noop},
    {"MiscSvrInfo_PI", MiscSvrInfo_PI, noop},
    {"ModDataObjMeta_PI", ModDataObjMeta_PI, noop},
    {"authRequestOut_PI", authRequestOut_PI, noop},
    {"authResponseInp_PI", authResponseInp_PI, noop},
    {"CollInpNew_PI", CollInpNew_PI, noop},
    {"ExecMyRuleInp_PI", ExecMyRuleInp_PI, noop},
    {"simpleQueryInp_PI", simpleQueryInp_PI, noop},
    {"generalAdminInp_PI", generalAdminInp_PI, noop},
    {"authCheckInp_PI", authCheckInp_PI, noop},
    {"authCheckOut_PI", authCheckOut_PI, noop},
    {"modAccessControlInp_PI", modAccessControlInp_PI, noop},
    {"ModAVUMetadataInp_PI", ModAVUMetadataInp_PI, noop},
    {"RULE_EXEC_MOD_INP_PI", RULE_EXEC_MOD_INP_PI, noop},
    {"RULE_EXEC_DEL_INP_PI", RULE_EXEC_DEL_INP_PI, noop},
    {"RULE_EXEC_SUBMIT_INP_PI", RULE_EXEC_SUBMIT_INP_PI, noop},
    {"simpleQueryOut_PI", simpleQueryOut_PI, noop},
    {"RegReplica_PI", RegReplica_PI, noop},
    {"UnregDataObj_PI", UnregDataObj_PI, noop},
    {"ExecCmd_PI", ExecCmd_PI, noop},
    {"ExecCmd241_PI", ExecCmd241_PI, noop},
    {"ExecCmdOut_PI", ExecCmdOut_PI, noop},
    {"SubStructFileFdOpr_PI", SubStructFileFdOpr_PI, noop},
    {"SubStructFileLseekInp_PI", SubStructFileLseekInp_PI, noop},
    {"SubStructFileRenameInp_PI", SubStructFileRenameInp_PI, noop},
    {"getTempPasswordOut_PI", getTempPasswordOut_PI, noop},
    {"GetXmsgTicketInp_PI", GetXmsgTicketInp_PI, noop},
    {"SendXmsgInp_PI", SendXmsgInp_PI, noop},
    {"StructFileOprInp_PI", StructFileOprInp_PI, noop},
    {"gsiAuthRequestOut_PI", gsiAuthRequestOut_PI, noop},
    {"StructFileExtAndRegInp_PI", StructFileExtAndRegInp_PI, noop},
    {"ChkObjPermAndStat_PI", ChkObjPermAndStat_PI, noop},
    {"userAdminInp_PI", userAdminInp_PI, noop},
    {"OpenStat_PI", OpenStat_PI, noop},
    {"fileStageSyncInp_PI", fileStageSyncInp_PI, noop},
    {"generalRowInsertInp_PI", generalRowInsertInp_PI, noop},
    {"generalRowPurgeInp_PI", generalRowPurgeInp_PI, noop},
    {"krbAuthRequestOut_PI", krbAuthRequestOut_PI, noop},
    {"getRescQuotaInp_PI", getRescQuotaInp_PI, noop},
    {"rescQuota_PI", rescQuota_PI, noop},
    {"BulkOprInp_PI", BulkOprInp_PI, noop},
    {"endTransactionInp_PI", endTransactionInp_PI, noop},
    {"ProcStatInp_PI", ProcStatInp_PI, noop},
    {"specificQueryInp_PI", specificQueryInp_PI, noop},
    {"ticketAdminInp_PI", ticketAdminInp_PI, noop},
    {"getTempPasswordForOtherInp_PI", getTempPasswordForOtherInp_PI, noop},
    {"getTempPasswordForOtherOut_PI", getTempPasswordForOtherOut_PI, noop},
    /* NETCDF PI */
#if 0 // NETCDF_CLIENT
    {"NcOpenInp_PI", NcOpenInp_PI, noop},
    {"NcCloseInp_PI", NcCloseInp_PI, noop},
    {"NcInqIdInp_PI", NcInqIdInp_PI, noop},
    {"NcInqWithIdOut_PI", NcInqWithIdOut_PI, noop},
    {"NcGetVarInp_PI", NcGetVarInp_PI, noop},
    {"NcGetVarOut_PI", NcGetVarOut_PI, noop},
    {"NcGenDimOut_PI", NcGenDimOut_PI, noop},
    {"NcGenAttOut_PI", NcGenAttOut_PI, noop},
    {"NcGenVarOut_PI", NcGenVarOut_PI, noop},
    {"NcInqInp_PI", NcInqInp_PI, noop},
    {"NcInqOut_PI", NcInqOut_PI, noop},
    {"NcInqGrpsInp_PI", NcInqGrpsInp_PI, noop},
    {"NcInqGrpsOut_PI", NcInqGrpsOut_PI, noop},
    {"NcRegGlobalAttrInp_PI", NcRegGlobalAttrInp_PI, noop},
    {"NcAggElement_PI", NcAggElement_PI, noop},
    {"NcAggInfo_PI", NcAggInfo_PI, noop},
    {"NcArchTimeSeriesInp_PI", NcArchTimeSeriesInp_PI, noop},
#endif
    /* endof NETCDF_CLIENT */
#ifdef OOI_CI
    {"OoiGenServReqInp_PI", OoiGenServReqInp_PI, noop},
    {"OoiGenServReqOut_PI", OoiGenServReqOut_PI, noop},
#endif

    {"pamAuthRequestInp_PI", pamAuthRequestInp_PI, noop},
    {"pamAuthRequestOut_PI", pamAuthRequestOut_PI, noop},
    {"authPlugReqInp_PI", authPlugReqInp_PI, noop},
    {"authPlugReqOut_PI", authPlugReqOut_PI, noop},
    {"getHierarchyForRescInp_PI", getHierarchyForRescInp_PI, noop},
    {"getHierarchyForRescOut_PI", getHierarchyForRescOut_PI, noop},
    {"sslStartInp_PI", sslStartInp_PI, noop},
    {"sslEndInp_PI", sslEndInp_PI, noop},
    {"getLimitedPasswordInp_PI", getLimitedPasswordInp_PI, noop},
    {"getLimitedPasswordOut_PI", getLimitedPasswordOut_PI, noop},
    {"fileSyncOut_PI", fileSyncOut_PI, noop},
    {"fileRenameOut_PI", fileRenameOut_PI, noop},
    {PACK_TABLE_END_PI, ( char * ) NULL, noop},
};

#endif	/* API_PACK_TABLE_H */
