/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* fileFstat.h - This file may be generated by a program or script
 */

#ifndef FILE_FSTAT_H
#define FILE_FSTAT_H

/* This is a low level file type API call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"

#include "fileDriver.h"

typedef struct {
    int fileInx;
} fileFstatInp_t;
    
#define fileFstatInp_PI "int fileInx;"

#if defined(RODS_SERVER)
#define RS_FILE_FSTAT rsFileFstat
/* prototype for the server handler */
int
rsFileFstat (rsComm_t *rsComm, fileFstatInp_t *fileFstatInp, 
rodsStat_t **fileFstatOut);
int
_rsFileFstat (rsComm_t *rsComm, fileFstatInp_t *fileFstatInp,
rodsStat_t **fileFstatOut);
int
remoteFileFstat (rsComm_t *rsComm, fileFstatInp_t *fileFstatInp,
rodsStat_t **fileFstatOut, rodsServerHost_t *rodsServerHost);
#else
#define RS_FILE_FSTAT NULL
#endif

/* prototype for the client call */
int
rcFileFstat (rcComm_t *conn, fileFstatInp_t *fileFstatInp, 
rodsStat_t **fileFstatOut);

#endif	/* FILE_FSTAT_H */
