/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* fileFsync.h - This file may be generated by a program or script
 */

#ifndef FILE_FSYNC_H
#define FILE_FSYNC_H

/* This is a low level file type API call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"

#include "fileDriver.h"

typedef struct {
    int fileInx;
} fileFsyncInp_t;
    
#define fileFsyncInp_PI "int fileInx;"

#if defined(RODS_SERVER)
#define RS_FILE_FSYNC rsFileFsync
/* prototype for the server handler */
int
rsFileFsync (rsComm_t *rsComm, fileFsyncInp_t *fileFsyncInp);
int
_rsFileFsync (rsComm_t *rsComm, fileFsyncInp_t *fileFsyncInp);
int
remoteFileFsync (rsComm_t *rsComm, fileFsyncInp_t *fileFsyncInp,
rodsServerHost_t *rodsServerHost);
#else
#define RS_FILE_FSYNC NULL
#endif

/* prototype for the client call */
int
rcFileFsync (rcComm_t *conn, fileFsyncInp_t *fileFsyncInp);

#endif	/* FILE_FSYNC_H */
