/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* fileGet.h - This file may be generated by a program or script
 */

#ifndef FILE_GET_H
#define FILE_GET_H

/* This is a low level file type API call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"

#include "fileDriver.h"
#include "fileOpen.h"

#if defined(RODS_SERVER)
#define RS_FILE_GET rsFileGet
/* prototype for the server handler */
int
rsFileGet (rsComm_t *rsComm, fileOpenInp_t *fileGetInp, 
bytesBuf_t *fileGetOutBBuf);
int
_rsFileGet (rsComm_t *rsComm, fileOpenInp_t *fileGetInp, 
bytesBuf_t *fileGetOutBBuf);
int
remoteFileGet (rsComm_t *rsComm, fileOpenInp_t *fileGetInp, 
bytesBuf_t *fileGetOutBBuf, rodsServerHost_t *rodsServerHost);
#else
#define RS_FILE_GET NULL
#endif

/* prototype for the client call */
int
rcFileGet (rcComm_t *conn, fileOpenInp_t *fileGetInp, 
bytesBuf_t *fileGetOutBBuf);

#endif	/* FILE_GET_H */
