/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* l3FileGetSingleBuf.h - This dataObj may be generated by a program or script
 */

#ifndef L3_FILE_GET_SINGLE_BUF_H
#define L3_FILE_GET_SINGLE_BUF_H

/* This is a Object File I/O call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"
#include "dataObjGet.h"

#if defined(RODS_SERVER)
#define RS_L3_FILE_GET_SINGLE_BUF rsL3FileGetSingleBuf
/* prototype for the server handler */
int
rsL3FileGetSingleBuf (rsComm_t *rsComm, int *l1descInx, 
bytesBuf_t *dataObjOutBBuf);
#else
#define RS_L3_FILE_GET_SINGLE_BUF NULL
#endif

#ifdef  __cplusplus
extern "C" {
#endif

/* prototype for the client call */
/* rcL3FileGetSingleBuf - remote call for l3FileGetSingleBuf for cross zone
 * single buffer get.
 * Input -
 *   rcComm_t *conn - The client connection handle.
 *   return value - The status of the operation.
 */
int
rcL3FileGetSingleBuf (rcComm_t *conn, int l1descInx,
bytesBuf_t *dataObjOutBBuf);

#ifdef  __cplusplus
}
#endif

#endif	/* L3_FILE_GET_SINGLE_BUF_H */
