/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* fileRead.h - This file may be generated by a program or script
 */

#ifndef STREAM_READ_H__
#define STREAM_READ_H__

/* This is a Object File I/O API call */

#include "rcConnect.h"
#include "objInfo.h"
#include "fileRead.h"

#if defined(RODS_SERVER)
#define RS_STREAM_READ rsStreamRead
/* prototype for the server handler */
int
rsStreamRead( rsComm_t *rsComm, fileReadInp_t *streamReadInp,
              bytesBuf_t *streamReadOutBBuf );
#else
#define RS_STREAM_READ NULL
#endif

#ifdef __cplusplus
extern "C" {
#endif
/* prototype for the client call */
int
rcStreamRead( rcComm_t *conn, fileReadInp_t *streamReadInp,
              bytesBuf_t *streamReadOutBBuf );
#ifdef __cplusplus
}
#endif

#endif	// STREAM_READ_H__
