/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* structFileExtract.h - This file may be generated by a program or script
 */

#ifndef STRUCT_FILE_EXTRACT_HPP
#define STRUCT_FILE_EXTRACT_HPP

/* This is a Object File I/O call */

#include "rods.hpp"
#include "rcMisc.hpp"
#include "procApiRequest.hpp"
#include "apiNumber.hpp"
#include "structFileSync.hpp"

#if defined(RODS_SERVER)
#define RS_STRUCT_FILE_EXTRACT rsStructFileExtract
/* prototype for the server handler */
int
rsStructFileExtract( rsComm_t *rsComm, structFileOprInp_t *structFileOprInp );
int
_rsStructFileExtract( rsComm_t *rsComm, structFileOprInp_t *structFileOprInp );
int
remoteStructFileExtract( rsComm_t *rsComm,
                         structFileOprInp_t *structFileOprInp, rodsServerHost_t *rodsServerHost );
#else
#define RS_STRUCT_FILE_EXTRACT NULL
#endif

/* prototype for the client call */
int
rcStructFileExtract( rcComm_t *conn, structFileOprInp_t *structFileOprInp );
int
procCacheDir( rsComm_t *rsComm, char *cacheDir, char *resource, int oprType, char* hier ); // JMC - backport 4657
#endif	/* STRUCT_FILE_EXTRACT_H */
