/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* apiHeaderAll.h - This is a script generated header file which contains
 * all the api header files */

#ifndef API_HEADER_ALL_H__
#define API_HEADER_ALL_H__

#include "getMiscSvrInfo.h"
#include "fileCreate.h"
#include "fileOpen.h"
#include "fileWrite.h"
#include "fileClose.h"
#include "fileLseek.h"
#include "fileRead.h"
#include "fileUnlink.h"
#include "fileMkdir.h"
#include "fileChmod.h"
#include "fileRmdir.h"
#include "fileStat.h"
#include "dataObjLock.h" // JMC - backport 4599
#include "fileGetFsFreeSpace.h"
#include "fileOpendir.h"
#include "fileClosedir.h"
#include "fileReaddir.h"
#include "dataObjCreate.h"
#include "dataObjOpen.h"
#include "dataObjRead.h"
#include "dataObjWrite.h"
#include "dataObjClose.h"
#include "dataObjPut.h"
#include "dataPut.h"
#include "dataObjGet.h"
#include "dataGet.h"
#include "dataObjRepl.h"
#include "filePut.h"
#include "fileGet.h"
#include "dataCopy.h"
#include "dataObjLseek.h"
#include "dataObjCopy.h"
#include "simpleQuery.h"
#include "dataObjUnlink.h"
#include "collCreate.h"
#include "generalAdmin.h"
#include "fileChksum.h"
#include "chkNVPathPerm.h"
#include "genQuery.h"
#include "authRequest.h"
#include "authResponse.h"
#include "authCheck.h"
#include "regColl.h"
#include "regDataObj.h"
#include "unregDataObj.h"
#include "regReplica.h"
#include "modDataObjMeta.h"
#include "modAVUMetadata.h"
#include "fileRename.h"
#include "modAccessControl.h"
#include "ruleExecSubmit.h"
#include "ruleExecDel.h"
#include "ruleExecMod.h"
#include "execMyRule.h"
#include "oprComplete.h"
#include "dataObjRename.h"
#include "dataObjRsync.h"
#include "dataObjChksum.h"
#include "phyPathReg.h"
#include "dataObjPhymv.h"
#include "dataObjTrim.h"
#include "objStat.h"
#include "execCmd.h"
#include "subStructFileCreate.h"
#include "subStructFileOpen.h"
#include "subStructFileRead.h"
#include "subStructFileWrite.h"
#include "subStructFileClose.h"
#include "subStructFileUnlink.h"
#include "subStructFileStat.h"
#include "subStructFileLseek.h"
#include "subStructFileRename.h"
#include "querySpecColl.h"
#include "getTempPassword.h"
#include "modColl.h"
#include "subStructFileMkdir.h"
#include "subStructFileRmdir.h"
#include "subStructFileOpendir.h"
#include "subStructFileReaddir.h"
#include "subStructFileClosedir.h"
#include "dataObjTruncate.h"
#include "fileTruncate.h"
#include "subStructFileTruncate.h"
#include "generalUpdate.h"
#include "subStructFileGet.h"
#include "subStructFilePut.h"
#include "syncMountedColl.h"
#include "structFileSync.h"
#include "openCollection.h"
#include "readCollection.h"
#include "closeCollection.h"
#include "collRepl.h"
#include "rmColl.h"
#include "structFileExtract.h"
#include "structFileExtAndReg.h"
#include "structFileBundle.h"
#include "chkObjPermAndStat.h"
#include "userAdmin.h"
#include "getRemoteZoneResc.h"
#include "dataObjOpenAndStat.h"
#include "l3FileGetSingleBuf.h"
#include "l3FilePutSingleBuf.h"
#include "dataObjCreateAndStat.h"
#include "fileStageToCache.h"
#include "fileSyncToArch.h"
#include "generalRowInsert.h"
#include "generalRowPurge.h"
#include "phyBundleColl.h"
#include "unbunAndRegPhyBunfile.h"
#include "getHostForPut.h"
#include "getRescQuota.h"
#include "bulkDataObjReg.h"
#include "bulkDataObjPut.h"
#include "endTransaction.h"
#include "procStat.h"
#include "streamRead.h"
#include "specificQuery.h"
#include "streamClose.h"
#include "getHostForGet.h"
#include "ticketAdmin.h"
#include "getTempPasswordForOther.h"
#include "getLimitedPassword.h"
#include "pamAuthRequest.h"
#include "sslStart.h"
#include "sslEnd.h"


// =-=-=-=-=-=-=-
// necessary for FUSE
#include "dataObjTruncate.h"
#include "fileTruncate.h"
#include "subStructFileTruncate.h"

// =-=-=-=-=-=-=-
// pluggable authentication
#include "authPluginRequest.h"
#include "getHierarchyForResc.h"

#include "get_hier_from_leaf_id.h"
#include "set_round_robin_context.h"
#include "exec_rule_expression.h"

#endif	// API_HEADER_ALL_H__
