TARGET = libssl.so

SRCS = libssl.cpp

HEADERS = 

EXTRALIBS = ../../../iRODS/lib/core/obj/eirods_plugin_base.o \
            ../../../iRODS/lib/core/obj/eirods_buffer_encryption.o 

include ../Makefile.base
