TARGET = libpam.so

SRCS = libpam.cpp

HEADERS = 

EXTRALIBS = ../../../iRODS/lib/core/obj/irods_plugin_base.o \
            ../../../iRODS/lib/api/obj/rcAuthPluginRequest.o

include ../Makefile.base
