#ifndef IRODS_GENQUERY2_SCANNER_HPP
#define IRODS_GENQUERY2_SCANNER_HPP

#include "parser.hpp" // Generated by Bison.

#ifndef yyFlexLexerOnce
#  include <FlexLexer.h>
#endif // yyFlexLexerOnce

#include <iosfwd> // For std::istream and std::ostream.

namespace irods::experimental::genquery2
{
    class driver;

    class scanner : public yyFlexLexer
    {
      public:
        auto yylex(driver& _driver) -> yy::parser::symbol_type;
    }; // class scanner
} // namespace irods::experimental::genquery2

#endif // IRODS_GENQUERY2_SCANNER_HPP
