/* ip2locationClientLib.c
   Generated by gSOAP 2.7.9l from ip2locationMS_wsdl.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "ip2locationC.c"
#include "ip2locationClient.c"

/* End of ip2locationClientLib.c */
