// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef uninst_h
#define uninst_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "gui-common.h"
extern Fl_Double_Window *UninstallWindow;
#include <FL/Fl_Box.H>
extern Fl_Box *Title[4];
#include <FL/Fl_Wizard.H>
extern Fl_Wizard *Wizard;
#include <FL/Fl_Group.H>
#include <FL/Fl_Help_View.H>
extern Fl_Help_View *ReadmeFile;
#include <FL/Fl_Check_Browser.H>
extern void list_cb(Fl_Check_Browser*, void*);
extern Fl_Check_Browser *SoftwareList;
extern Fl_Box *SoftwareSize;
#include <FL/Fl_Button.H>
extern Fl_Button *RemoveAllButton;
extern Fl_Button *RemoveNoneButton;
#include <FL/Fl_Browser.H>
extern Fl_Browser *ConfirmList;
extern Fl_Group *Pane[4];
#include <FL/Fl_Progress.H>
extern Fl_Progress *RemovePercent;
extern Fl_Browser *RemoveLog;
extern Fl_Box *WelcomeImage;
extern Fl_Button *PrevButton;
extern void next_cb(Fl_Button*, void*);
extern Fl_Button *NextButton;
extern Fl_Button *CancelButton;
Fl_Double_Window* make_window();
#endif
