TARGET = libtcp.so

SRCS = libtcp.cpp

HEADERS = 

EXTRALIBS = ../../../iRODS/lib/core/obj/irods_plugin_base.o \
            ../../../iRODS/lib/core/obj/irods_network_plugin.o

include ../Makefile.base

