TARGET = libmsiobjget_irods.so

SRCS = libmsiobjget_irods.cpp

HEADERS = 

EXTRALIBS = ../../../../iRODS/lib/api/obj/rcDataObjCreate.o ../../../../iRODS/lib/api/obj/rcDataObjOpen.o ../../../../iRODS/lib/api/obj/rcDataObjClose.o ../../../../iRODS/lib/api/obj/rcDataObjRead.o ../../../../iRODS/lib/api/obj/rcDataObjWrite.o

include ../Makefile.base
