#!/bin/sh
#
# Control the iRODS servers.
#
# Usage is:
#	irodsctl [args] [options]
#
# Type 'irodsctl --help' for a list of options.
#
# This shell script runs the 'irods_control' Python script.
#
IRODS_HOME=$(dirname $0)
python $IRODS_HOME/scripts/python/irods_control.py $*
exit $?

