// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* stockQuoteMS_wsdl.h
   Generated by wsdl2h 2.8.3 from stockQuote.wsdl and typemap.dat
   2011-08-08 19:56:47 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2010 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on stockQuoteMS_wsdl.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://www.webserviceX.NET/                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/

// This service uses SOAP 1.2 namespaces:
//gsoap SOAP-ENV schema namespace:	http://www.w3.org/2003/05/soap-envelope
//gsoap SOAP-ENC schema namespace:	http://www.w3.org/2003/05/soap-encoding

/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://www.webserviceX.NET/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://www.webserviceX.NET/"
//gsoap ns1   schema namespace:	http://www.webserviceX.NET/
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://www.webserviceX.NET/                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://www.webserviceX.NET/                                              *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "http://www.webserviceX.NET/":GetQuote

/// "http://www.webserviceX.NET/":GetQuote is a complexType.
struct _ns1__GetQuote
{
/// Element symbol of type xs:string.
    char*                                symbol                         0;	///< Optional element.
};


/// Top-level root element "http://www.webserviceX.NET/":GetQuoteResponse

/// "http://www.webserviceX.NET/":GetQuoteResponse is a complexType.
struct _ns1__GetQuoteResponse
{
/// Element GetQuoteResult of type xs:string.
    char*                                GetQuoteResult                 0;	///< Optional element.
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://www.webserviceX.NET/                                              *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://www.webserviceX.NET/":string of type xs:string.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://www.webserviceX.NET/                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	StockQuoteSoap 
//gsoap ns2  service type:	StockQuoteSoap 
//gsoap ns2  service port:	http://www.webservicex.net/stockquote.asmx 
//gsoap ns2  service namespace:	http://www.webserviceX.NET/StockQuoteSoap 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap ns3  service name:	StockQuoteSoap12 
//gsoap ns3  service type:	StockQuoteSoap 
//gsoap ns3  service port:	http://www.webservicex.net/stockquote.asmx 
//gsoap ns3  service namespace:	http://www.webserviceX.NET/StockQuoteSoap12 
//gsoap ns3  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref StockQuoteSoap

  - @ref StockQuoteSoap12

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page StockQuoteSoap Binding "StockQuoteSoap"

@section StockQuoteSoap_operations Operations of Binding  "StockQuoteSoap"

  - @ref __ns2__GetQuote

@section StockQuoteSoap_ports Endpoints of Binding  "StockQuoteSoap"

  - http://www.webservicex.net/stockquote.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/**

@page StockQuoteSoap12 Binding "StockQuoteSoap12"

@section StockQuoteSoap12_operations Operations of Binding  "StockQuoteSoap12"

  - @ref __ns3__GetQuote

@section StockQuoteSoap12_ports Endpoints of Binding  "StockQuoteSoap12"

  - http://www.webservicex.net/stockquote.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   StockQuoteSoap                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns2__GetQuote                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns2__GetQuote" of service binding "StockQuoteSoap"

/**

Operation details:

Get Stock quote for a company Symbol

  - SOAP document/literal style messaging

  - SOAP action="http://www.webserviceX.NET/GetQuote"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns2__GetQuote(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__GetQuote*              ns1__GetQuote,
    // response parameters:
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns2__GetQuote(
    struct soap *soap,
    // request parameters:
    struct _ns1__GetQuote*              ns1__GetQuote,
    // response parameters:
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse
  );
@endcode

*/

//gsoap ns2  service method-style:	GetQuote document
//gsoap ns2  service method-encoding:	GetQuote literal
//gsoap ns2  service method-action:	GetQuote http://www.webserviceX.NET/GetQuote
int __ns2__GetQuote(
    struct _ns1__GetQuote*              ns1__GetQuote,	///< Request parameter
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   StockQuoteSoap12                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns3__GetQuote                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns3__GetQuote" of service binding "StockQuoteSoap12"

/**

Operation details:

Get Stock quote for a company Symbol

  - SOAP document/literal style messaging

  - SOAP action="http://www.webserviceX.NET/GetQuote"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns3__GetQuote(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__GetQuote*              ns1__GetQuote,
    // response parameters:
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns3__GetQuote(
    struct soap *soap,
    // request parameters:
    struct _ns1__GetQuote*              ns1__GetQuote,
    // response parameters:
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse
  );
@endcode

*/

//gsoap ns3  service method-style:	GetQuote document
//gsoap ns3  service method-encoding:	GetQuote literal
//gsoap ns3  service method-action:	GetQuote http://www.webserviceX.NET/GetQuote
int __ns3__GetQuote(
    struct _ns1__GetQuote*              ns1__GetQuote,	///< Request parameter
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns1 Top-level root elements of schema "http://www.webserviceX.NET/"

  - <ns1:GetQuote> @ref _ns1__GetQuote
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__GetQuote(struct soap*, struct _ns1__GetQuote*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__GetQuote(struct soap*, struct _ns1__GetQuote*);
    @endcode

  - <ns1:GetQuoteResponse> @ref _ns1__GetQuoteResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__GetQuoteResponse(struct soap*, struct _ns1__GetQuoteResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__GetQuoteResponse(struct soap*, struct _ns1__GetQuoteResponse*);
    @endcode

  - <ns1:string> (use wsdl2h option -g to auto-generate)

*/

/* End of stockQuoteMS_wsdl.h */
