/* stockQuoteClient.c
   Generated by gSOAP 2.8.3 from stockQuoteMS_wsdl.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "stockQuoteH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) stockQuoteClient.c ver 2.8.3 2011-08-08 19:56:59 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__GetQuote(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetQuote *ns1__GetQuote, struct _ns1__GetQuoteResponse *ns1__GetQuoteResponse)
{	struct __ns2__GetQuote soap_tmp___ns2__GetQuote;
	if (!soap_endpoint)
		soap_endpoint = "http://www.webservicex.net/stockquote.asmx";
	if (!soap_action)
		soap_action = "http://www.webserviceX.NET/GetQuote";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetQuote.ns1__GetQuote = ns1__GetQuote;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetQuote(soap, &soap_tmp___ns2__GetQuote);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetQuote(soap, &soap_tmp___ns2__GetQuote, "-ns2:GetQuote", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetQuote(soap, &soap_tmp___ns2__GetQuote, "-ns2:GetQuote", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetQuoteResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetQuoteResponse(soap, ns1__GetQuoteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetQuoteResponse(soap, ns1__GetQuoteResponse, "ns1:GetQuoteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__GetQuote(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetQuote *ns1__GetQuote, struct _ns1__GetQuoteResponse *ns1__GetQuoteResponse)
{	struct __ns3__GetQuote soap_tmp___ns3__GetQuote;
	if (!soap_endpoint)
		soap_endpoint = "http://www.webservicex.net/stockquote.asmx";
	if (!soap_action)
		soap_action = "http://www.webserviceX.NET/GetQuote";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__GetQuote.ns1__GetQuote = ns1__GetQuote;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__GetQuote(soap, &soap_tmp___ns3__GetQuote);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__GetQuote(soap, &soap_tmp___ns3__GetQuote, "-ns3:GetQuote", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__GetQuote(soap, &soap_tmp___ns3__GetQuote, "-ns3:GetQuote", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetQuoteResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetQuoteResponse(soap, ns1__GetQuoteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetQuoteResponse(soap, ns1__GetQuoteResponse, "ns1:GetQuoteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of stockQuoteClient.c */
