/* stockQuoteClientLib.c
   Generated by gSOAP 2.8.3 from stockQuoteMS_wsdl.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

/** Use this file in your project build instead of the two files stockQuoteC.c and stockQuoteClient.c. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "stockQuoteC.c"
#include "stockQuoteClient.c"

/* End of stockQuoteClientLib.c */
