//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Inquisitor.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_BLAH                        101
#define IDD_DIALOGBAR2                  103
#define IDD_DIALOGBAR4                  103
#define IDD_DIALOGBAR                   103
#define IDR_ADDRESSBAR_TMPL             104
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_BLAH                        128
#define IDR_INQUISTYPE                  129
#define IDB_VIEW_ICONS                  133
#define IDB_VIEW_ICONS_LARGE            134
#define IDI_WINI                        136
#define IDR_TOOLBAR2                    137
#define IDR_H                           137
#define IDD_LOGIN                       141
#define IDD_DIALOGBAR1                  142
#define IDD_DIALOGBAR3                  143
#define IDR_LISTVIEWS                   144
#define IDB_VIEW_ICONS_LARGE1           145
#define IDR_MFCAVI                      151
#define IDD_QUERY                       154
#define IDI_ICON1                       157
#define IDI_ICON2                       161
#define IDI_ICON3                       162
#define IDI_ICON4                       165
#define IDI_ICON5                       166
#define IDI_ICON6                       167
#define IDI_ICON7                       168
#define IDI_ICON8                       169
#define IDI_ICON9                       170
#define IDI_ICON10                      171
#define IDI_ICON11                      172
#define IDR_AVI1                        177
#define IDD_GENERIC_DIALOG              178
#define IDR_AVI2                        182
#define IDD_ACCESS_CTRL                 186
#define IDD_ACCESS_CTRL_USER_ADD        188
#define IDD_ACCESS_CTRL_GROUP_ADD       189
#define IDD_PROGRESS_DLG                192
#define IDD_PROGRESSBAR                 193
#define IDI_ICON12                      194
#define IDD_DIALOG1                     195
#define IDD_METADATA                    195
#define IDI_ICON13                      196
#define IDI_ICON14                      197
#define IDI_ICON15                      199
#define IDB_BITMAP1                     200
#define IDB_GO                          202
#define IDI_ICON16                      203
#define IDI_ICON17                      204
#define IDD_DS                          206
#define IDB_BITMAP2                     218
#define IDB_ABOUT_PIC                   224
#define IDI_ICON18                      228
#define IDI_ICON19                      229
#define IDI_ICON20                      230
#define IDI_ICON21                      234
#define IDI_ICON22                      235
#define IDI_ICON23                      236
#define IDI_ICON24                      237
#define IDI_ICON25                      238
#define IDI_ICON26                      239
#define IDI_ICON27                      240
#define IDI_ICON28                      241
#define IDI_ICON29                      242
#define IDI_ICON30                      243
#define IDI_ICON31                      244
#define IDB_BITMAP3                     247
#define IDB_BITMAP4                     248
#define IDB_BITMAP5                     249
#define IDB_BITMAP6                     250
#define IDB_BITMAP7                     251
#define IDB_VIEW_GREYED                 256
#define IDB_VIEW_NORMAL                 257
#define IDB_VIEW_SELECTED               258
#define IDC_LIST1                       1000
#define IDC_LOGIN_NEW                   1006
#define IDC_LOGIN_REMOVE                1007
#define IDC_LOGIN_PASSWORD              1009
#define IDC_TREE_STACK                  1016
#define IDC_STATIC1                     1019
#define IDC_STATIC2                     1020
#define IDC_STATIC3                     1021
#define IDC_STATIC4                     1022
#define IDC_STATIC5                     1023
#define IDC_STATIC7                     1025
#define IDC_LOGIN_AUTH                  1027
#define IDC_METADATA_ATTRIBUTE          1028
#define IDC_METADATA_VALUE              1030
#define IDC_LOGIN_NAME                  1031
#define IDC_LOGIN_HOST                  1032
#define IDC_LOGIN_DOMAIN                1033
#define IDC_LOGIN_ZONE                  1033
#define IDC_LOGIN_PORT                  1034
#define IDC_RESOURCE                    1036
#define IDC_QUERY_ATTRIBUTE             1037
#define IDC_QUERY_VALUE                 1038
#define IDC_QUERY_OPERATION             1039
#define IDC_QUERY_ADD                   1040
#define IDC_QUERY_REMOVE                1041
#define IDC_QUERY_AND                   1042
#define IDC_QUERY_OR                    1043
#define IDC_QUERY_LIST                  1044
#define IDC_EDIT1                       1045
#define IDC_LIST2                       1059
#define IDC_USER_ADD_USER               1059
#define IDC_CHECK1                      1062
#define IDC_RECURSIVEAC                 1062
#define IDC_CHECK2                      1063
#define IDC_ACCESS_CTRL_ADD             1064
#define IDC_ACCESS_CTRL_REMOVE          1067
#define IDC_ACCESS_CTRL_CONSTRAINT      1068
#define IDC_ACCESS_CTRL_LIST            1069
#define IDC_USER_ADD_DOMAIN             1070
#define IDC_CONSTRAINT                  1072
#define IDC_PROGRESS                    1075
#define IDC_PROGRESS_MESSAGE            1078
#define IDC_STATIC10                    1081
#define IDC_METADATA_DLG_VALUE          1083
#define IDC_METADATA_DLG_ATTRIBUTE      1084
#define IDC_GO_BUTTON                   1086
#define IDC_DS2_PROGRESS                1088
#define IDC_DS_STATIC                   1089
#define IDC_LOGIN_DEMO                  1090
#define IDC_STATIC1111                  1095
#define IDC_STATIC0001                  1096
#define IDC_LISTZONE                    1101
#define IDC_PATHBAR                     1103
#define IDC_PATHGO                      1104
#define IDC_HOTKEY1                     1106
#define ID_QUERY                        32771
#define ID_UPLOAD                       32773
#define ID_DOWNLOAD                     32774
#define ID_BUTTON32775                  32775
#define ID_BUTTON32776                  32776
#define ID_COPY                         32777
#define ID_BUTTON32778                  32778
#define ID_DELETE                       32778
#define ID_TREE_HOME                    32791
#define ID_TREE_UP                      32792
#define ID_BUTTON32793                  32793
#define ID_BACK                         32793
#define ID_BUTTON32794                  32794
#define ID_FORWARD                      32794
#define ID_STOP                         32813
#define ID_REFRESH                      32816
#define ID_REPLICATE                    32823
#define ID_SYNCHRONIZE                  32824
#define ID_ACCESS_CTRL                  32825
#define ID_NEW_COLLECTION               32826
#define ID_BUTTON32827                  32827
#define ID_NEW_CONTAINER                32828
#define ID_DISCONNECT                   32830
#define ID_METADATA                     32838
#define ID_RENAME                       32843
#define ID_DEFAULT_RESOURCE             32845
#define ID_COMMENT                      32846
#define ID_OPEN                         32847
#define ID_OPEN_WIDTH                   32848
#define ID_CHANGE_PASSWORD              32849
#define ID_SELECT_ALL                   32850
#define ID_INVERT_SELECTION             32851
#define ID_VIEW_WINIBAR                 32852
#define ID_VIEW_QUICKBAR                32853
#define ID_VIEW_JUMPVIEWBAR             32854
#define ID_OPENTREE                     32856
#define ID_BUTTON32894                  32894
#define ID_NEW_META                     32914
#define ID_GETPATH                      32920
#define ID_UPLOADFOLDER                 32922
#define ID_FOOFIGHTER                   32927
#define ID_STATUS_TEXT                  61204
#define ID_STATUS_PBAR                  61208
#define ID_DOWNLOAD_SUCCESSFUL          61209
#define ID_DOWNLOAD_FAILED              61210
#define IDS_DELETED                     61211
#define IDS_NOT_DELETED                 61212
#define ID_UPLOAD_SUCCESSFUL            61213
#define ID_UPLOAD_FAILED                61214
#define ID_EXECUTE_SUCCESSFUL           61215
#define ID_EXECUTE_FAILED               61216
#define IDS_STATUS_COUNT                61217
#define IDS_ACCESS_CTRL_USERS           61218
#define IDS_ACCESS_CTRL_GROUPS          61219

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        262
#define _APS_NEXT_COMMAND_VALUE         32928
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
