/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* apiHeaderAll.h - This is a script generated header file which contains
 * all the api header files */

#ifndef API_HEADER_ALL_H__
#define API_HEADER_ALL_H__

#include "irods/getMiscSvrInfo.h"
#include "irods/fileCreate.h"
#include "irods/fileOpen.h"
#include "irods/fileWrite.h"
#include "irods/fileClose.h"
#include "irods/fileLseek.h"
#include "irods/fileRead.h"
#include "irods/fileUnlink.h"
#include "irods/fileMkdir.h"
#include "irods/fileChmod.h"
#include "irods/fileRmdir.h"
#include "irods/fileStat.h"
#include "irods/dataObjLock.h" // JMC - backport 4599
#include "irods/fileGetFsFreeSpace.h"
#include "irods/fileOpendir.h"
#include "irods/fileClosedir.h"
#include "irods/fileReaddir.h"
#include "irods/dataObjCreate.h"
#include "irods/dataObjOpen.h"
#include "irods/dataObjRead.h"
#include "irods/dataObjWrite.h"
#include "irods/dataObjClose.h"
#include "irods/dataObjPut.h"
#include "irods/dataPut.h"
#include "irods/dataObjGet.h"
#include "irods/dataGet.h"
#include "irods/dataObjRepl.h"
#include "irods/filePut.h"
#include "irods/fileGet.h"
#include "irods/dataCopy.h"
#include "irods/dataObjLseek.h"
#include "irods/dataObjCopy.h"
#include "irods/simpleQuery.h"
#include "irods/dataObjUnlink.h"
#include "irods/collCreate.h"
#include "irods/generalAdmin.h"
#include "irods/fileChksum.h"
#include "irods/chkNVPathPerm.h"
#include "irods/genQuery.h"
#include "irods/authRequest.h"
#include "irods/authResponse.h"
#include "irods/authCheck.h"
#include "irods/regColl.h"
#include "irods/regDataObj.h"
#include "irods/unregDataObj.h"
#include "irods/regReplica.h"
#include "irods/modDataObjMeta.h"
#include "irods/modAVUMetadata.h"
#include "irods/fileRename.h"
#include "irods/modAccessControl.h"
#include "irods/ruleExecSubmit.h"
#include "irods/ruleExecDel.h"
#include "irods/ruleExecMod.h"
#include "irods/execMyRule.h"
#include "irods/oprComplete.h"
#include "irods/dataObjRename.h"
#include "irods/dataObjRsync.h"
#include "irods/dataObjChksum.h"
#include "irods/phyPathReg.h"
#include "irods/dataObjPhymv.h"
#include "irods/dataObjTrim.h"
#include "irods/objStat.h"
#include "irods/execCmd.h"
#include "irods/subStructFileCreate.h"
#include "irods/subStructFileOpen.h"
#include "irods/subStructFileRead.h"
#include "irods/subStructFileWrite.h"
#include "irods/subStructFileClose.h"
#include "irods/subStructFileUnlink.h"
#include "irods/subStructFileStat.h"
#include "irods/subStructFileLseek.h"
#include "irods/subStructFileRename.h"
#include "irods/querySpecColl.h"
#include "irods/getTempPassword.h"
#include "irods/modColl.h"
#include "irods/subStructFileMkdir.h"
#include "irods/subStructFileRmdir.h"
#include "irods/subStructFileOpendir.h"
#include "irods/subStructFileReaddir.h"
#include "irods/subStructFileClosedir.h"
#include "irods/dataObjTruncate.h"
#include "irods/fileTruncate.h"
#include "irods/subStructFileTruncate.h"
#include "irods/generalUpdate.h"
#include "irods/subStructFileGet.h"
#include "irods/subStructFilePut.h"
#include "irods/syncMountedColl.h"
#include "irods/structFileSync.h"
#include "irods/openCollection.h"
#include "irods/readCollection.h"
#include "irods/closeCollection.h"
#include "irods/collRepl.h"
#include "irods/rmColl.h"
#include "irods/structFileExtract.h"
#include "irods/structFileExtAndReg.h"
#include "irods/structFileBundle.h"
#include "irods/chkObjPermAndStat.h"
#include "irods/userAdmin.h"
#include "irods/getRemoteZoneResc.h"
#include "irods/dataObjOpenAndStat.h"
#include "irods/l3FileGetSingleBuf.h"
#include "irods/l3FilePutSingleBuf.h"
#include "irods/dataObjCreateAndStat.h"
#include "irods/fileStageToCache.h"
#include "irods/fileSyncToArch.h"
#include "irods/generalRowInsert.h"
#include "irods/generalRowPurge.h"
#include "irods/phyBundleColl.h"
#include "irods/unbunAndRegPhyBunfile.h"
#include "irods/getHostForPut.h"
#include "irods/getRescQuota.h"
#include "irods/bulkDataObjReg.h"
#include "irods/bulkDataObjPut.h"
#include "irods/endTransaction.h"
#include "irods/procStat.h"
#include "irods/streamRead.h"
#include "irods/specificQuery.h"
#include "irods/streamClose.h"
#include "irods/getHostForGet.h"
#include "irods/ticketAdmin.h"
#include "irods/getTempPasswordForOther.h"
#include "irods/getLimitedPassword.h"
#include "irods/pamAuthRequest.h"
#include "irods/sslStart.h"
#include "irods/sslEnd.h"


// =-=-=-=-=-=-=-
// necessary for FUSE
#include "irods/dataObjTruncate.h"
#include "irods/fileTruncate.h"
#include "irods/subStructFileTruncate.h"

// =-=-=-=-=-=-=-
// pluggable authentication
#include "irods/authPluginRequest.h"
#include "irods/getHierarchyForResc.h"

#include "irods/get_hier_from_leaf_id.h"
#include "irods/exec_rule_expression.h"

#endif	// API_HEADER_ALL_H__
