DROP TRIGGER tg_ext_data_delete on r_data_main;
DROP TRIGGER tg_ext_coll_delete on r_coll_main;
DROP TRIGGER tg_ext_resc_delete on r_resc_main;
DROP TRIGGER tg_ext_zone_delete on r_zone_main;

DROP TABLE ext_audit_actions CASCADE;
DROP INDEX idx_ext_audit1;
DROP TABLE ext_coll_historical CASCADE;
DROP INDEX idx_ext_coll2;
DROP INDEX idx_ext_coll3;
DROP TABLE ext_data_historical CASCADE;
DROP INDEX idx_ext_data1;
DROP INDEX idx_ext_data2;
DROP TABLE ext_resc_historical CASCADE;
DROP INDEX idx_ext_resc1;
DROP INDEX idx_ext_resc2;
DROP TABLE ext_zone_historical CASCADE;
DROP INDEX idx_ext_zone1;
DROP INDEX idx_ext_zone2;
DROP FUNCTION tg_ext_audit_delete();
DROP VIEW vw_ext_data;
DROP VIEW vw_ext_coll;
DROP VIEW vw_ext_resc;
DROP VIEW vw_ext_audit;
DROP LANGUAGE plpgsql;
