#!/bin/sh -e

set -e

IRODS_HOME=/usr/share/eirods/iRODS
IRODS_CTL=./irodsctl

cd $IRODS_HOME


case $1 in
status)
    $IRODS_CTL status
    ;;
start)
    setuid eirods $IRODS_CTL start
    ;;
stop)
    setuid eirods $IRODS_CTL stop
    ;;
restart)
    setuid eirods $IRODS_CTL restart
    ;;
*)
    echo "/etc/init.d/e-irods :: [$1] is not supported."
    exit 1
esac
