#!/bin/sh -e

set -e

IRODS_HOME=/var/lib/e-irods/iRODS
IRODS_CTL=./irodsctl

cd $IRODS_HOME


case $1 in
status)
    $IRODS_CTL status
    ;;
start)
    su --shell=/bin/bash -c "$IRODS_CTL istart" eirods
    ;;
stop)
    su --shell=/bin/bash -c "$IRODS_CTL istop" eirods
    ;;
restart)
    su --shell=/bin/bash -c "$IRODS_CTL irestart" eirods
    ;;
force-reload)
    su --shell=/bin/bash -c "$IRODS_CTL irestart" eirods
    ;;
*)
    echo "/etc/init.d/e-irods :: [$1] is not supported."
    exit 1
esac
