#!/bin/sh
#
# See "man chkconfig" for information on next two lines (RedHatCompatible Only)
# chkconfig: 2345 90 10
# description: Enterprise iRODS
#
#
# Following lines are in conformance with LSB 1.2 spec
### BEGIN INIT INFO
# Provides:          eirods
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manages the E-iRODS service
# Description:       Manages the E-iRODS service
### END INIT INFO

set -e

IRODS_HOME=/var/lib/eirods/iRODS
IRODS_CTL=./irodsctl

cd $IRODS_HOME

DETECTEDOS=`../packaging/find_os.sh`

case $1 in
status)
    su --shell=/bin/bash -c "$IRODS_CTL status" eirods
    ;;
start)
    su --shell=/bin/bash -c "$IRODS_CTL istart" eirods
    if [ "$DETECTEDOS" == "RedHatCompatible" -o "$DETECTEDOS" == "SuSE" ] ; then
        touch /var/lock/subsys/eirods
    fi
    ;;
stop)
    su --shell=/bin/bash -c "$IRODS_CTL istop" eirods
    if [ "$DETECTEDOS" == "RedHatCompatible" -o "$DETECTEDOS" == "SuSE" ] ; then
        rm /var/lock/subsys/eirods
    fi
    ;;
restart)
    su --shell=/bin/bash -c "$IRODS_CTL irestart" eirods
    if [ "$DETECTEDOS" == "RedHatCompatible" -o "$DETECTEDOS" == "SuSE" ] ; then
        touch /var/lock/subsys/eirods
    fi
    ;;
force-reload)
    su --shell=/bin/bash -c "$IRODS_CTL irestart" eirods
    if [ "$DETECTEDOS" == "RedHatCompatible" -o "$DETECTEDOS" == "SuSE" ] ; then
        touch /var/lock/subsys/eirods
    fi
    ;;
*)
    echo "/etc/init.d/eirods :: [$1] is not supported." 1>&2
    echo "Usage: /etc/init.d/eirods {start|stop|status|restart|force-reload}" 1>&2
    exit 1
esac
