#!/bin/bash
#
# Check that the code follows a consistent code style
#

# Check for existence of astyle, and error out if not present.
if ! builtin type -P astyle; then
      echo "Did not find astyle, please install it before continuing."
      exit 1
fi

GITROOT=$( git rev-parse --show-toplevel )

source $GITROOT/packaging/astyleparams
cd $GITROOT

echo "-- iRODS Pre-Commit Style Check - BEGIN"
for file in `git diff-index --cached --name-only HEAD --diff-filter=ACMR| egrep "\.c$|\.h$|\.hpp$|\.cpp$"` ; do
    # nf is the temporary checkout. This makes sure we check against the
    # revision in the index (and not the checked out version).
    nf=`git checkout-index --temp ${file} | cut -f 1`
    newfile=`mktemp -t ${nf}.XXXXXX` || exit 1
    astyle ${ASTYLE_PARAMETERS} < $nf > $newfile 2>> /dev/null
    diff -u -p "${nf}" "${newfile}"
    r=$?
    rm "${newfile}"
    rm "${nf}"
    if [ $r != 0 ] ; then
        echo "========================================================================================="
        echo "Code style error in: $file"
        echo ""
        echo "1. Fix it up (make above suggested changes)."
        echo "      astyle ${ASTYLE_PARAMETERS} $file"
        echo "2. Restage file:"
        echo "      git add $file"
        echo "3. Try to git commit again."
        echo ""
        echo "========================================================================================="
        exit 1
    fi
done
echo "-- iRODS Pre-Commit Style Check - COMPLETE"
