# TODO static dev libraries?
# TODO symlinks for h -> hpp headers?

install(
  TARGETS
    RodsAPIs
  ARCHIVE
    DESTINATION ${CMAKE_INSTALL_LIBDIR}
    COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
  )

set(
  IRODS_GENERATED_HEADERS
  ${CMAKE_CURRENT_BINARY_DIR}/lib/core/include/irods/irods_default_paths.hpp
  ${CMAKE_CURRENT_BINARY_DIR}/lib/core/include/irods/irods_version.h
  ${CMAKE_CURRENT_BINARY_DIR}/lib/core/include/irods/rodsVersion.h
  ${CMAKE_CURRENT_BINARY_DIR}/lib/core/include/irods/server_control_plane_command.hpp
  )

set(
  IRODS_LIB_CORE_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/alignPointer.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/apiHandler.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/authentication_plugin_framework.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/base64.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/bunUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/capped_memory_resource.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/chksumUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/client_connection.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/connection_pool.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/cpUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/dispatch_processor.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/dns_cache.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/dstream.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/entity.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/experimental_plugin_framework.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/fixed_buffer_resource.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/fsckUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/future.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/getRodsEnv.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/getUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/guiProgressCallback.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/hostname_cache.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_assert.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_at_scope_exit.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_auth_constants.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_auth_factory.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_auth_manager.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_auth_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_generic_auth_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_auth_plugin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_auth_types.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_buffer_encryption.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_children_parser.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_client_api_table.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_client_server_negotiation.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_configuration_keywords.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_configuration_parser.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_environment_properties.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_error.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_exception.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_first_class_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_get_full_path_for_config_file.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_gsi_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_hash.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_hashtable.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_hierarchy_parser.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_krb_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_kvp_string_parser.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_lexical_cast.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_list.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_load_plugin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_log.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_logger.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_logger.tpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_lookup_table.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_native_auth_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_network_constants.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_network_factory.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_network_manager.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_network_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_network_plugin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_network_types.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_osauth_auth_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_pack_table.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_pam_auth_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_parse_command_line_options.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_path_recursion.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_pluggable_auth_scheme.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_plugin_base.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_plugin_context.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_plugin_name_generator.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_query.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_random.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_serialization.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_server_properties.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_ssl_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_stacktrace.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_state_table.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_string_tokenize.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_tcp_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_threads.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/irods_virtual_path.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/key_value_proxy.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/lifetime_manager.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/lsUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/mcollUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/metadata.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/microservice.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/miscUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/mkdirUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/msParam.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/mvUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/obf.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/objInfo.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/osauth.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/packStruct.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/parallel_transfer_engine.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/parseCommandLine.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/phybunUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/phymvUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/procApiRequest.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/putUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/query_builder.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/query_processor.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rcConnect.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rcGlobalExtern.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rcMisc.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rcPortalOpr.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/regUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/region.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/replUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/replica.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/replica_proxy.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rmdirUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rmUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rmtrashUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rods.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsClient.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsDef.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsError.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsErrorTable.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsGenQuery.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsGenQueryNames.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsGeneralUpdate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsKeyWdDef.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsLog.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsPackInstruct.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsPackTable.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsPath.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsQuota.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsType.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rodsUser.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/rsyncUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/scanUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/shared_memory_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/sockComm.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/sockCommNetworkInterface.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/socket_wrapper.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/sslSockComm.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/stringOpr.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/termiosUtil.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/thread_pool.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/trimUtil.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/version.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/with_durability.hpp
  )

set(
  IRODS_LIB_ADMINISTRATION_USER_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/administration/user/include/irods/group.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/administration/user/include/irods/user.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/administration/user/include/irods/user_administration.hpp
  )

set(
  IRODS_LIB_ADMINISTRATION_RESOURCE_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/administration/resource/include/irods/resource_administration.hpp
  )

set(
  IRODS_LIB_HASHER_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/hasher/include/irods/HashStrategy.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/hasher/include/irods/Hasher.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/hasher/include/irods/MD5Strategy.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/hasher/include/irods/SHA256Strategy.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/hasher/include/irods/checksum.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/hasher/include/irods/irods_hasher_factory.hpp
  )

set(
  IRODS_LIB_API_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/apiHeaderAll.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/apiNumber.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/apiNumberData.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/apiNumberMap.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/apiPackTable.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/apiTable.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/authCheck.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/authPluginRequest.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/authRequest.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/authResponse.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/atomic_apply_acl_operations.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/atomic_apply_metadata_operations.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/authenticate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/bulkDataObjPut.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/bulkDataObjReg.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/chkNVPathPerm.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/chkObjPermAndStat.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/client_hints.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/closeCollection.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/collCreate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/collRepl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/data_object_finalize.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/data_object_modify_info.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataCopy.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataGet.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjChksum.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjClose.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjCopy.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjCreate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjCreateAndStat.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjGet.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjInpOut.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjLock.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjLseek.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjOpen.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjOpenAndStat.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjPhymv.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjPut.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjRead.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjRename.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjRepl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjRsync.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjTrim.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjTruncate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjUnlink.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataObjWrite.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/dataPut.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/endTransaction.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/execCmd.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/execMyRule.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/exec_rule_expression.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileChksum.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileChmod.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileClose.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileClosedir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileCreate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileGet.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileGetFsFreeSpace.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileLseek.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileMkdir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileOpen.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileOpendir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/filePut.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileRead.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileReaddir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileRename.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileRmdir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileStageToCache.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileStat.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileSyncToArch.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileTruncate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileUnlink.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/fileWrite.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/genQuery.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/get_file_descriptor_info.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/generalAdmin.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/generalRowInsert.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/generalRowPurge.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/generalUpdate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getHierarchyForResc.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getHostForGet.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getHostForPut.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getLimitedPassword.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getMiscSvrInfo.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getRemoteZoneResc.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getRescQuota.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getTempPassword.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/getTempPasswordForOther.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/get_hier_from_leaf_id.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/ies_client_hints.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/l3FileGetSingleBuf.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/l3FilePutSingleBuf.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/modAVUMetadata.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/modAccessControl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/modColl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/modDataObjMeta.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/objStat.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/openCollection.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/oprComplete.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/pamAuthRequest.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/phyBundleColl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/phyPathReg.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/procStat.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/querySpecColl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/readCollection.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/regColl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/regDataObj.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/regReplica.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/register_physical_path.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/rmColl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/ruleExecDel.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/ruleExecMod.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/ruleExecSubmit.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/server_report.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/simpleQuery.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/specificQuery.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/sslEnd.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/sslStart.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/streamClose.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/streamRead.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/structFileBundle.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/structFileExtAndReg.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/structFileExtract.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/structFileSync.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileClose.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileClosedir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileCreate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileGet.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileLseek.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileMkdir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileOpen.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileOpendir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFilePut.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileRead.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileReaddir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileRename.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileRmdir.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileStat.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileTruncate.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileUnlink.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/subStructFileWrite.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/syncMountedColl.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/replica_open.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/replica_close.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/ticketAdmin.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/touch.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/unbunAndRegPhyBunfile.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/unregDataObj.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/userAdmin.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/api/include/irods/zone_report.h
  )

set(
  IRODS_LIB_RBUDP_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/rbudp/include/irods/QUANTAnet_rbudpBase_c.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/rbudp/include/irods/QUANTAnet_rbudpReceiver_c.h
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/rbudp/include/irods/QUANTAnet_rbudpSender_c.h
  )

set(
  IRODS_SERVER_API_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rs_atomic_apply_acl_operations.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rs_atomic_apply_metadata_operations.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rs_data_object_finalize.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rs_get_file_descriptor_info.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rs_register_physical_path.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rs_replica_open.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rs_replica_close.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rs_touch.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsAuthCheck.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsAuthPluginRequest.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsAuthRequest.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsAuthResponse.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsAuthenticate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsBulkDataObjPut.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsBulkDataObjReg.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsChkNVPathPerm.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsChkObjPermAndStat.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsClientHints.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsCloseCollection.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsCollCreate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsCollRepl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataCopy.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataGet.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjChksum.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjClose.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjCopy.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjCreate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjCreateAndStat.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjGet.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjLock.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjLseek.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjOpen.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjOpenAndStat.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjPhymv.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjPut.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjRead.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjRename.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjRepl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjRsync.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjTrim.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjTruncate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjUnlink.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataObjWrite.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsDataPut.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsEndTransaction.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsExecCmd.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsExecMyRule.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsExecRuleExpression.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileChksum.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileChmod.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileClose.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileClosedir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileCreate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileGet.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileGetFsFreeSpace.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileLseek.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileMkdir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileOpen.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileOpendir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFilePut.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileRead.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileReaddir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileRename.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileRmdir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileStageToCache.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileStat.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileSyncToArch.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileTruncate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileUnlink.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsFileWrite.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGenQuery.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGeneralAdmin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGeneralRowInsert.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGeneralRowPurge.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGeneralUpdate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetHierFromLeafId.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetHierarchyForResc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetHostForGet.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetHostForPut.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetLimitedPassword.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetMiscSvrInfo.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetRemoteZoneResc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetRescQuota.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetTempPassword.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsGetTempPasswordForOther.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsIESClientHints.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsL3FileGetSingleBuf.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsL3FilePutSingleBuf.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsModAVUMetadata.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsModAccessControl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsModColl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsModDataObjMeta.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsObjStat.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsOpenCollection.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsOprComplete.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsPamAuthRequest.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsPhyBundleColl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsPhyPathReg.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsProcStat.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsQuerySpecColl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsReadCollection.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsRegColl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsRegDataObj.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsRegReplica.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsRmColl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsRuleExecDel.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsRuleExecMod.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsRuleExecSubmit.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsServerReport.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSimpleQuery.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSpecificQuery.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSslEnd.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSslStart.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsStreamClose.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsStreamRead.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsStructFileBundle.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsStructFileExtAndReg.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsStructFileExtract.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsStructFileSync.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileClose.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileClosedir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileCreate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileGet.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileLseek.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileMkdir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileOpen.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileOpendir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFilePut.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileRead.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileReaddir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileRename.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileRmdir.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileStat.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileTruncate.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileUnlink.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSubStructFileWrite.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsSyncMountedColl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsTicketAdmin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsUnbunAndRegPhyBunfile.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsUnregDataObj.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsUserAdmin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/api/include/irods/rsZoneReport.hpp
  )

set(
  IRODS_SERVER_CORE_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/administration_utilities.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/atomic_apply_database_operations.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/client_api_whitelist.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/collection.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/dataObjOpr.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/replica_access_table.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/replica_state_table.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/fileOpr.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/finalize_utilities.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/initServer.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_api_calling_functions.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_collection_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_data_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_database_constants.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_database_factory.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_database_manager.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_database_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_database_plugin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_database_types.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_dynamic_cast.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_file_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_generic_database_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_get_l1desc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_linked_list_iterator.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_mysql_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_oracle_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_physical_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_postgres_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_resource_backport.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_resource_constants.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_resource_manager.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_resource_plugin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_resource_plugin_impostor.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_resource_redirect.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_resource_types.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_rs_comm_query.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_server_api_call.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_server_api_table.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_server_control_plane.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_server_state.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/irods_structured_object.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/json_deserialization.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/json_serialization.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/logical_locking.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/miscServerFunct.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/objDesc.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/objMetaOpr.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/physPath.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/procLog.h
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/resource.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/rodsAgent.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/rodsConnect.h
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/rsApiHandler.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/rsGlobalExtern.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/rsIcatOpr.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/rsLog.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/scoped_client_identity.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/scoped_permission.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/scoped_privileged_client.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/server_utilities.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/specColl.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/user_validation_utilities.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/core/include/irods/voting.hpp
  )

set(
  IRODS_SERVER_ICAT_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/server/icat/include/irods/icatDefines.h
  ${CMAKE_CURRENT_SOURCE_DIR}/server/icat/include/irods/icatGlobalsExtern.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/icat/include/irods/icatHighLevelRoutines.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/icat/include/irods/icatStructs.hpp
  )

set(
  IRODS_SERVER_RE_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/irods_ms_plugin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/irods_re_plugin.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/irods_re_namespaceshelper.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/irods_re_structs.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/irods_re_ruleexistshelper.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/irods_re_serialization.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/locks.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/msiHelper.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/reAction.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/reDataObjOpr.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/reDefines.h
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/reIn2p3SysRule.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/reNaraMetaData.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/reSysDataObjOpr.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/server/re/include/irods/reconstants.hpp
  )

set(
  IRODS_SERVER_DRIVERS_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/server/drivers/include/fileDriver.hpp
  )

set(
  IRODS_SERVER_MAIN_SERVER_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/server/main_server/include/irods/rodsServer.hpp
  )

set(
  IRODS_SERVER_DELAY_SERVER_INCLUDE_HEADERS
  ${CMAKE_CURRENT_SOURCE_DIR}/server/delay_server/include/irods/irodsReServer.hpp
  )

install(
  FILES
  ${IRODS_GENERATED_HEADERS}
  ${IRODS_LIB_CORE_INCLUDE_HEADERS}
  ${IRODS_LIB_ADMINISTRATION_USER_INCLUDE_HEADERS}
  ${IRODS_LIB_ADMINISTRATION_RESOURCE_INCLUDE_HEADERS}
  ${IRODS_LIB_HASHER_INCLUDE_HEADERS}
  ${IRODS_LIB_API_INCLUDE_HEADERS}
  ${IRODS_LIB_RBUDP_INLUDE_HEADERS}
  ${IRODS_SERVER_API_INCLUDE_HEADERS}
  ${IRODS_SERVER_CORE_INCLUDE_HEADERS}
  ${IRODS_SERVER_ICAT_INCLUDE_HEADERS}
  ${IRODS_SERVER_RE_INCLUDE_HEADERS}
  ${IRODS_SERVER_DRIVERS_INCLUDE_HEADERS}
  ${IRODS_SERVER_MAIN_SERVER_INCLUDE_HEADERS}
  ${IRODS_SERVER_DELAY_SERVER_INCLUDE_HEADERS}
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/irods
  COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
  )

install(
  FILES
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/collection_entry.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/collection_iterator.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/config.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/copy_options.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/detail.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/filesystem.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/filesystem.tpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/filesystem_error.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/object_status.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/path.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/path_traits.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/permissions.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/filesystem/include/irods/filesystem/recursive_collection_iterator.hpp
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/irods/filesystem
  COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
  )

install(
  FILES
  ${CMAKE_CURRENT_SOURCE_DIR}/plugins/api/include/irods/plugins/api/api_plugin_number.h
  ${CMAKE_CURRENT_SOURCE_DIR}/plugins/api/include/irods/plugins/api/api_plugin_number_map.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/plugins/api/include/irods/plugins/api/api_plugin_number_data.h
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/irods/plugins/api
  COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
  )

install(
  FILES
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/transport/transport/transport.hpp
  ${CMAKE_CURRENT_SOURCE_DIR}/lib/core/include/irods/transport/transport/default_transport.hpp
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/irods/transport
  COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
  )

install(
  EXPORT
  IRODSTargets
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/irods/cmake
  COMPONENT ${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}
  )

set(CPACK_DEBIAN_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME_UPPERCASE}_PACKAGE_NAME "irods-dev")
set(CPACK_DEBIAN_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME_UPPERCASE}_PACKAGE_DEPENDS "${IRODS_DEVELOP_DEPENDENCIES_STRING}, irods-runtime (= ${CPACK_DEBIAN_PACKAGE_VERSION}-${CPACK_DEBIAN_PACKAGE_RELEASE}), libssl-dev")
set(CPACK_DEBIAN_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME_UPPERCASE}_PACKAGE_PROVIDES "irods-dev (= ${CPACK_DEBIAN_PACKAGE_VERSION})")

set(CPACK_RPM_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}_PACKAGE_NAME "irods-devel")
set(CPACK_RPM_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}_PACKAGE_REQUIRES "${IRODS_DEVELOP_DEPENDENCIES_STRING}, irods-runtime = ${CPACK_RPM_PACKAGE_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}")
if (IRODS_LINUX_DISTRIBUTION_NAME STREQUAL "centos")
  set(CPACK_RPM_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}_PACKAGE_REQUIRES "${CPACK_RPM_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}_PACKAGE_REQUIRES}, openssl-devel")
elseif (IRODS_LINUX_DISTRIBUTION_NAME STREQUAL "opensuse")
  set(CPACK_RPM_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}_PACKAGE_REQUIRES "${CPACK_RPM_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}_PACKAGE_REQUIRES}, libopenssl-devel")
endif()
set(CPACK_RPM_${IRODS_PACKAGE_COMPONENT_DEVELOPMENT_NAME}_PACKAGE_OBSOLETES "irods-dev")
