/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/

/**
 * @file	imageMS.h
 *
 * @brief	Declarations for the msiImage* microservices.
 */

#ifndef IMAGEMS_H
#define IMAGEMS_H

#include "rods.h"
#include "reGlobalsExtern.h"
#include "rsGlobalExtern.h"
#include "rcGlobalExtern.h"






int msiImageConvert( msParam_t *sourceParameter, msParam_t* sourceOptions,
	msParam_t *destinationParameter, msParam_t* destinationOptions,
	ruleExecInfo_t *rei );

int msiImageGetProperties( msParam_t *sourceParameter, msParam_t* sourceOptions,
	msParam_t *listParam, ruleExecInfo_t *rei );

int msiImageScale( msParam_t *sourceParameter, msParam_t* sourceOptions,
	msParam_t* xScaleFactor, msParam_t* yScaleFactor,
	msParam_t *destinationParameter, msParam_t* destinationOptions,
	ruleExecInfo_t *rei );





/**
 * Image properties used to describe an image or to control how an image
 * is processed.
 *
 * The properties are based upon EXIF (EXchangable Image File format), a
 * standard for metadata in images.  EXIF is widely supported in cameras
 * and in software that works with camera images (such as PhotoShop
 * and ImageMagick).  While these are all standard properties, few image
 * files will have them all.  Some will have none of them.
 *
 * This EXIF property list is derived from ImageMagick's "property.c"
 * file in the ImageMagick 6.3.5 distribution.
 *
 * The image microservices that read properties are case insensitive.
 *
 * @see	http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html
 */
#define PROPERTY_IMAGE_PREFIX				"image."

#define PROPERTY_IMAGE_FORMAT				"image.Format"
#define PROPERTY_IMAGE_COMPRESSION			"image.Compression"
#define PROPERTY_IMAGE_COMPRESSIONQUALITY		"image.CompressionQuality"
#define PROPERTY_IMAGE_INTERLACE			"image.Interlace"
#define PROPERTY_IMAGE_COLORSPACE			"image.ColorSpace"
#define PROPERTY_IMAGE_DEPTH				"image.Depth"
#define PROPERTY_IMAGE_COLORS				"image.Colors"
#define PROPERTY_IMAGE_GAMMA				"image.Gamma"
#define PROPERTY_IMAGE_XRESOLUTION			"image.XResolution"
#define PROPERTY_IMAGE_YRESOLUTION			"image.YResolution"
#define PROPERTY_IMAGE_RESOLUTIONUNIT			"image.ResolutionUnit"
#define PROPERTY_IMAGE_ORIENTATION			"image.Orientation"
#define PROPERTY_IMAGE_ROWS				"image.Rows"
#define PROPERTY_IMAGE_COLUMNS				"image.Columns"

#define PROPERTY_IMAGE_EXIF_INTEROPERABILITYINDEX	"image.exif.InteroperabilityIndex"
#define PROPERTY_IMAGE_EXIF_INTEROPERABILITYVERSION	"image.exif.InteroperabilityVersion"
#define PROPERTY_IMAGE_EXIF_IMAGEWIDTH			"image.exif.ImageWidth"
#define PROPERTY_IMAGE_EXIF_IMAGELENGTH			"image.exif.ImageLength"
#define PROPERTY_IMAGE_EXIF_BITSPERSAMPLE		"image.exif.BitsPerSample"
#define PROPERTY_IMAGE_EXIF_COMPRESSION			"image.exif.Compression"
#define PROPERTY_IMAGE_EXIF_PHOTOMETRICINTERPRETATION	"image.exif.PhotometricInterpretation"
#define PROPERTY_IMAGE_EXIF_FILLORDER			"image.exif.FillOrder"
#define PROPERTY_IMAGE_EXIF_DOCUMENTNAME		"image.exif.DocumentName"
#define PROPERTY_IMAGE_EXIF_IMAGEDESCRIPTION		"image.exif.ImageDescription"
#define PROPERTY_IMAGE_EXIF_MAKE			"image.exif.Make"
#define PROPERTY_IMAGE_EXIF_MODEL			"image.exif.Model"
#define PROPERTY_IMAGE_EXIF_STRIPOFFSETS		"image.exif.StripOffsets"
#define PROPERTY_IMAGE_EXIF_ORIENTATION			"image.exif.Orientation"
#define PROPERTY_IMAGE_EXIF_SAMPLESPERPIXEL		"image.exif.SamplesPerPixel"
#define PROPERTY_IMAGE_EXIF_ROWSPERSTRIP		"image.exif.RowsPerStrip"
#define PROPERTY_IMAGE_EXIF_STRIPBYTECOUNTS		"image.exif.StripByteCounts"
#define PROPERTY_IMAGE_EXIF_XRESOLUTION			"image.exif.XResolution"
#define PROPERTY_IMAGE_EXIF_YRESOLUTION			"image.exif.YResolution"
#define PROPERTY_IMAGE_EXIF_PLANARCONFIGURATION		"image.exif.PlanarConfiguration"
#define PROPERTY_IMAGE_EXIF_PAGENAME			"image.exif.PageName"
#define PROPERTY_IMAGE_EXIF_XPOSITION			"image.exif.XPosition"
#define PROPERTY_IMAGE_EXIF_YPOSITION			"image.exif.YPosition"
#define PROPERTY_IMAGE_EXIF_MINSAMPLEVALUE		"image.exif.MinSampleValue"
#define PROPERTY_IMAGE_EXIF_MAXSAMPLEVALUE		"image.exif.MaxSampleValue"
#define PROPERTY_IMAGE_EXIF_FREEOFFSETS			"image.exif.FreeOffsets"
#define PROPERTY_IMAGE_EXIF_FREEBYTECOUNTS		"image.exif.FreeByteCounts"
#define PROPERTY_IMAGE_EXIF_GRAYRESPONSEUNIT		"image.exif.GrayResponseUnit"
#define PROPERTY_IMAGE_EXIF_GRAYRESPONSECURVE		"image.exif.GrayResponseCurve"
#define PROPERTY_IMAGE_EXIF_T4OPTIONS			"image.exif.T4Options"
#define PROPERTY_IMAGE_EXIF_T6OPTIONS			"image.exif.T6Options"
#define PROPERTY_IMAGE_EXIF_RESOLUTIONUNIT		"image.exif.ResolutionUnit"
#define PROPERTY_IMAGE_EXIF_TRANSFERFUNCTION		"image.exif.TransferFunction"
#define PROPERTY_IMAGE_EXIF_SOFTWARE			"image.exif.Software"
#define PROPERTY_IMAGE_EXIF_DATETIME			"image.exif.DateTime"
#define PROPERTY_IMAGE_EXIF_ARTIST			"image.exif.Artist"
#define PROPERTY_IMAGE_EXIF_WHITEPOINT			"image.exif.WhitePoint"
#define PROPERTY_IMAGE_EXIF_PRIMARYCHROMATICITIES	"image.exif.PrimaryChromaticities"
#define PROPERTY_IMAGE_EXIF_COLORMAP			"image.exif.ColorMap"
#define PROPERTY_IMAGE_EXIF_HALFTONEHINTS		"image.exif.HalfToneHints"
#define PROPERTY_IMAGE_EXIF_TILEWIDTH			"image.exif.TileWidth"
#define PROPERTY_IMAGE_EXIF_TILELENGTH			"image.exif.TileLength"
#define PROPERTY_IMAGE_EXIF_TILEOFFSETS			"image.exif.TileOffsets"
#define PROPERTY_IMAGE_EXIF_TILEBYTECOUNTS		"image.exif.TileByteCounts"
#define PROPERTY_IMAGE_EXIF_SUBIFD			"image.exif.SubIFD"
#define PROPERTY_IMAGE_EXIF_INKSET			"image.exif.InkSet"
#define PROPERTY_IMAGE_EXIF_INKNAMES			"image.exif.InkNames"
#define PROPERTY_IMAGE_EXIF_NUMBEROFINKS		"image.exif.NumberOfInks"
#define PROPERTY_IMAGE_EXIF_DOTRANGE			"image.exif.DotRange"
#define PROPERTY_IMAGE_EXIF_TARGETPRINTER		"image.exif.TargetPrinter"
#define PROPERTY_IMAGE_EXIF_EXTRASAMPLE			"image.exif.ExtraSample"
#define PROPERTY_IMAGE_EXIF_SAMPLEFORMAT		"image.exif.SampleFormat"
#define PROPERTY_IMAGE_EXIF_SMINSAMPLEVALUE		"image.exif.SMinSampleValue"
#define PROPERTY_IMAGE_EXIF_SMAXSAMPLEVALUE		"image.exif.SMaxSampleValue"
#define PROPERTY_IMAGE_EXIF_TRANSFERRANGE		"image.exif.TransferRange"
#define PROPERTY_IMAGE_EXIF_CLIPPATH			"image.exif.ClipPath"
#define PROPERTY_IMAGE_EXIF_XCLIPPATHUNITS		"image.exif.XClipPathUnits"
#define PROPERTY_IMAGE_EXIF_YCLIPPATHUNITS		"image.exif.YClipPathUnits"
#define PROPERTY_IMAGE_EXIF_INDEXED			"image.exif.Indexed"
#define PROPERTY_IMAGE_EXIF_JPEGTABLES			"image.exif.JPEGTables"
#define PROPERTY_IMAGE_EXIF_OPIPROXY			"image.exif.OPIProxy"
#define PROPERTY_IMAGE_EXIF_JPEGPROC			"image.exif.JPEGProc"
#define PROPERTY_IMAGE_EXIF_JPEGINTERCHANGEFORMAT	"image.exif.JPEGInterchangeFormat"
#define PROPERTY_IMAGE_EXIF_JPEGINTERCHANGEFORMATLENGTH	"image.exif.JPEGInterchangeFormatLength"
#define PROPERTY_IMAGE_EXIF_JPEGRESTARTINTERVAL		"image.exif.JPEGRestartInterval"
#define PROPERTY_IMAGE_EXIF_JPEGLOSSLESSPREDICTORS	"image.exif.JPEGLosslessPredictors"
#define PROPERTY_IMAGE_EXIF_JPEGPOINTTRANSFORMS		"image.exif.JPEGPointTransforms"
#define PROPERTY_IMAGE_EXIF_JPEGQTABLES			"image.exif.JPEGQTables"
#define PROPERTY_IMAGE_EXIF_JPEGDCTABLES		"image.exif.JPEGDCTables"
#define PROPERTY_IMAGE_EXIF_JPEGACTABLES		"image.exif.JPEGACTables"
#define PROPERTY_IMAGE_EXIF_YCBCRCOEFFICIENTS		"image.exif.YCbCrCoefficients"
#define PROPERTY_IMAGE_EXIF_YCBCRSUBSAMPLING		"image.exif.YCbCrSubSampling"
#define PROPERTY_IMAGE_EXIF_YCBCRPOSITIONING		"image.exif.YCbCrPositioning"
#define PROPERTY_IMAGE_EXIF_REFERENCEBLACKWHITE		"image.exif.ReferenceBlackWhite"
#define PROPERTY_IMAGE_EXIF_EXTENSIBLEMETADATAPLATFORM	"image.exif.ExtensibleMetadataPlatform"
#define PROPERTY_IMAGE_EXIF_GAMMA			"image.exif.Gamma"
#define PROPERTY_IMAGE_EXIF_ICCPROFILEDESCRIPTOR	"image.exif.ICCProfileDescriptor"
#define PROPERTY_IMAGE_EXIF_SRGBRENDERINGINTENT		"image.exif.SRGBRenderingIntent"
#define PROPERTY_IMAGE_EXIF_IMAGETITLE			"image.exif.ImageTitle"
#define PROPERTY_IMAGE_EXIF_RESOLUTIONXUNIT		"image.exif.ResolutionXUnit"
#define PROPERTY_IMAGE_EXIF_RESOLUTIONYUNIT		"image.exif.ResolutionYUnit"
#define PROPERTY_IMAGE_EXIF_RESOLUTIONXLENGTHUNIT	"image.exif.ResolutionXLengthUnit"
#define PROPERTY_IMAGE_EXIF_RESOLUTIONYLENGTHUNIT	"image.exif.ResolutionYLengthUnit"
#define PROPERTY_IMAGE_EXIF_PRINTFLAGS			"image.exif.PrintFlags"
#define PROPERTY_IMAGE_EXIF_PRINTFLAGSVERSION		"image.exif.PrintFlagsVersion"
#define PROPERTY_IMAGE_EXIF_PRINTFLAGSCROP		"image.exif.PrintFlagsCrop"
#define PROPERTY_IMAGE_EXIF_PRINTFLAGSBLEEDWIDTH	"image.exif.PrintFlagsBleedWidth"
#define PROPERTY_IMAGE_EXIF_PRINTFLAGSBLEEDWIDTHSCALE	"image.exif.PrintFlagsBleedWidthScale"
#define PROPERTY_IMAGE_EXIF_HALFTONELPI			"image.exif.HalftoneLPI"
#define PROPERTY_IMAGE_EXIF_HALFTONELPIUNIT		"image.exif.HalftoneLPIUnit"
#define PROPERTY_IMAGE_EXIF_HALFTONEDEGREE		"image.exif.HalftoneDegree"
#define PROPERTY_IMAGE_EXIF_HALFTONESHAPE		"image.exif.HalftoneShape"
#define PROPERTY_IMAGE_EXIF_HALFTONEMISC		"image.exif.HalftoneMisc"
#define PROPERTY_IMAGE_EXIF_HALFTONESCREEN		"image.exif.HalftoneScreen"
#define PROPERTY_IMAGE_EXIF_JPEGQUALITY			"image.exif.JPEGQuality"
#define PROPERTY_IMAGE_EXIF_GRIDSIZE			"image.exif.GridSize"
#define PROPERTY_IMAGE_EXIF_THUMBNAILFORMAT		"image.exif.ThumbnailFormat"
#define PROPERTY_IMAGE_EXIF_THUMBNAILWIDTH		"image.exif.ThumbnailWidth"
#define PROPERTY_IMAGE_EXIF_THUMBNAILHEIGHT		"image.exif.ThumbnailHeight"
#define PROPERTY_IMAGE_EXIF_THUMBNAILCOLORDEPTH		"image.exif.ThumbnailColorDepth"
#define PROPERTY_IMAGE_EXIF_THUMBNAILPLANES		"image.exif.ThumbnailPlanes"
#define PROPERTY_IMAGE_EXIF_THUMBNAILRAWBYTES		"image.exif.ThumbnailRawBytes"
#define PROPERTY_IMAGE_EXIF_THUMBNAILSIZE		"image.exif.ThumbnailSize"
#define PROPERTY_IMAGE_EXIF_THUMBNAILCOMPRESSEDSIZE	"image.exif.ThumbnailCompressedSize"
#define PROPERTY_IMAGE_EXIF_COLORTRANSFERFUNCTION	"image.exif.ColorTransferFunction"
#define PROPERTY_IMAGE_EXIF_THUMBNAILDATA		"image.exif.ThumbnailData"
#define PROPERTY_IMAGE_EXIF_THUMBNAILIMAGEWIDTH		"image.exif.ThumbnailImageWidth"
#define PROPERTY_IMAGE_EXIF_THUMBNAILIMAGEHEIGHT	"image.exif.ThumbnailImageHeight"
#define PROPERTY_IMAGE_EXIF_THUMBNAILBITSPERSAMPLE	"image.exif.ThumbnailBitsPerSample"
#define PROPERTY_IMAGE_EXIF_THUMBNAILCOMPRESSION	"image.exif.ThumbnailCompression"
#define PROPERTY_IMAGE_EXIF_THUMBNAILPHOTOMETRICINTERP	"image.exif.ThumbnailPhotometricInterp"
#define PROPERTY_IMAGE_EXIF_THUMBNAILIMAGEDESCRIPTION	"image.exif.ThumbnailImageDescription"
#define PROPERTY_IMAGE_EXIF_THUMBNAILEQUIPMAKE		"image.exif.ThumbnailEquipMake"
#define PROPERTY_IMAGE_EXIF_THUMBNAILEQUIPMODEL		"image.exif.ThumbnailEquipModel"
#define PROPERTY_IMAGE_EXIF_THUMBNAILSTRIPOFFSETS	"image.exif.ThumbnailStripOffsets"
#define PROPERTY_IMAGE_EXIF_THUMBNAILORIENTATION	"image.exif.ThumbnailOrientation"
#define PROPERTY_IMAGE_EXIF_THUMBNAILSAMPLESPERPIXEL	"image.exif.ThumbnailSamplesPerPixel"
#define PROPERTY_IMAGE_EXIF_THUMBNAILROWSPERSTRIP	"image.exif.ThumbnailRowsPerStrip"
#define PROPERTY_IMAGE_EXIF_THUMBNAILSTRIPBYTESCOUNT	"image.exif.ThumbnailStripBytesCount"
#define PROPERTY_IMAGE_EXIF_THUMBNAILRESOLUTIONX	"image.exif.ThumbnailResolutionX"
#define PROPERTY_IMAGE_EXIF_THUMBNAILRESOLUTIONY	"image.exif.ThumbnailResolutionY"
#define PROPERTY_IMAGE_EXIF_THUMBNAILPLANARCONFIG	"image.exif.ThumbnailPlanarConfig"
#define PROPERTY_IMAGE_EXIF_THUMBNAILRESOLUTIONUNIT	"image.exif.ThumbnailResolutionUnit"
#define PROPERTY_IMAGE_EXIF_THUMBNAILTRANSFERFUNCTION	"image.exif.ThumbnailTransferFunction"
#define PROPERTY_IMAGE_EXIF_THUMBNAILSOFTWAREUSED	"image.exif.ThumbnailSoftwareUsed"
#define PROPERTY_IMAGE_EXIF_THUMBNAILDATETIME		"image.exif.ThumbnailDateTime"
#define PROPERTY_IMAGE_EXIF_THUMBNAILARTIST		"image.exif.ThumbnailArtist"
#define PROPERTY_IMAGE_EXIF_THUMBNAILWHITEPOINT		"image.exif.ThumbnailWhitePoint"
#define PROPERTY_IMAGE_EXIF_THUMBNAILPRIMARYCHROMATICITIES	"image.exif.ThumbnailPrimaryChromaticities"
#define PROPERTY_IMAGE_EXIF_THUMBNAILYCBCRCOEFFICIENTS	"image.exif.ThumbnailYCbCrCoefficients"
#define PROPERTY_IMAGE_EXIF_THUMBNAILYCBCRSUBSAMPLING	"image.exif.ThumbnailYCbCrSubsampling"
#define PROPERTY_IMAGE_EXIF_THUMBNAILYCBCRPOSITIONING	"image.exif.ThumbnailYCbCrPositioning"
#define PROPERTY_IMAGE_EXIF_THUMBNAILREFBLACKWHITE	"image.exif.ThumbnailRefBlackWhite"
#define PROPERTY_IMAGE_EXIF_THUMBNAILCOPYRIGHT		"image.exif.ThumbnailCopyRight"
#define PROPERTY_IMAGE_EXIF_LUMINANCETABLE		"image.exif.LuminanceTable"
#define PROPERTY_IMAGE_EXIF_CHROMINANCETABLE		"image.exif.ChrominanceTable"
#define PROPERTY_IMAGE_EXIF_FRAMEDELAY			"image.exif.FrameDelay"
#define PROPERTY_IMAGE_EXIF_LOOPCOUNT			"image.exif.LoopCount"
#define PROPERTY_IMAGE_EXIF_PIXELUNIT			"image.exif.PixelUnit"
#define PROPERTY_IMAGE_EXIF_PIXELPERUNITX		"image.exif.PixelPerUnitX"
#define PROPERTY_IMAGE_EXIF_PIXELPERUNITY		"image.exif.PixelPerUnitY"
#define PROPERTY_IMAGE_EXIF_PALETTEHISTOGRAM		"image.exif.PaletteHistogram"
#define PROPERTY_IMAGE_EXIF_RELATEDIMAGEFILEFORMAT	"image.exif.RelatedImageFileFormat"
#define PROPERTY_IMAGE_EXIF_RELATEDIMAGELENGTH		"image.exif.RelatedImageLength"
#define PROPERTY_IMAGE_EXIF_RELATEDIMAGEWIDTH		"image.exif.RelatedImageWidth"
#define PROPERTY_IMAGE_EXIF_IMAGEID			"image.exif.ImageID"
#define PROPERTY_IMAGE_EXIF_MATTEING			"image.exif.Matteing"
#define PROPERTY_IMAGE_EXIF_DATATYPE			"image.exif.DataType"
#define PROPERTY_IMAGE_EXIF_IMAGEDEPTH			"image.exif.ImageDepth"
#define PROPERTY_IMAGE_EXIF_TILEDEPTH			"image.exif.TileDepth"
#define PROPERTY_IMAGE_EXIF_CFAREPEATPATTERNDIM		"image.exif.CFARepeatPatternDim"
#define PROPERTY_IMAGE_EXIF_CFAPATTERN			"image.exif.CFAPattern"
#define PROPERTY_IMAGE_EXIF_BATTERYLEVEL		"image.exif.BatteryLevel"
#define PROPERTY_IMAGE_EXIF_CFAREPEATPATTERNDIM		"image.exif.CFARepeatPatternDim"
#define PROPERTY_IMAGE_EXIF_CFAPATTERN			"image.exif.CFAPattern"
#define PROPERTY_IMAGE_EXIF_BATTERYLEVEL		"image.exif.BatteryLevel"
#define PROPERTY_IMAGE_EXIF_COPYRIGHT			"image.exif.Copyright"
#define PROPERTY_IMAGE_EXIF_EXPOSURETIME		"image.exif.ExposureTime"
#define PROPERTY_IMAGE_EXIF_FNUMBER			"image.exif.FNumber"
#define PROPERTY_IMAGE_EXIF_IPTCNAA			"image.exif.IPTC/NAA"
#define PROPERTY_IMAGE_EXIF_IT8RASTERPADDING		"image.exif.IT8RasterPadding"
#define PROPERTY_IMAGE_EXIF_IT8COLORTABLE		"image.exif.IT8ColorTable"
#define PROPERTY_IMAGE_EXIF_IMAGERESOURCEINFORMATION	"image.exif.ImageResourceInformation"
#define PROPERTY_IMAGE_EXIF_EXIFOFFSET			"image.exif.ExifOffset"
#define PROPERTY_IMAGE_EXIF_INTERCOLORPROFILE		"image.exif.InterColorProfile"
#define PROPERTY_IMAGE_EXIF_EXPOSUREPROGRAM		"image.exif.ExposureProgram"
#define PROPERTY_IMAGE_EXIF_SPECTRALSENSITIVITY		"image.exif.SpectralSensitivity"
#define PROPERTY_IMAGE_EXIF_GPSINFO			"image.exif.GPSInfo"
#define PROPERTY_IMAGE_EXIF_ISOSPEEDRATINGS		"image.exif.ISOSpeedRatings"
#define PROPERTY_IMAGE_EXIF_OECF			"image.exif.OECF"
#define PROPERTY_IMAGE_EXIF_INTERLACE			"image.exif.Interlace"
#define PROPERTY_IMAGE_EXIF_TIMEZONEOFFSET		"image.exif.TimeZoneOffset"
#define PROPERTY_IMAGE_EXIF_SELFTIMERMODE		"image.exif.SelfTimerMode"
#define PROPERTY_IMAGE_EXIF_EXIFVERSION			"image.exif.ExifVersion"
#define PROPERTY_IMAGE_EXIF_DATETIMEORIGINAL		"image.exif.DateTimeOriginal"
#define PROPERTY_IMAGE_EXIF_DATETIMEDIGITIZED		"image.exif.DateTimeDigitized"
#define PROPERTY_IMAGE_EXIF_COMPONENTSCONFIGURATION	"image.exif.ComponentsConfiguration"
#define PROPERTY_IMAGE_EXIF_COMPRESSEDBITSPERPIXEL	"image.exif.CompressedBitsPerPixel"
#define PROPERTY_IMAGE_EXIF_SHUTTERSPEEDVALUE		"image.exif.ShutterSpeedValue"
#define PROPERTY_IMAGE_EXIF_APERTUREVALUE		"image.exif.ApertureValue"
#define PROPERTY_IMAGE_EXIF_BRIGHTNESSVALUE		"image.exif.BrightnessValue"
#define PROPERTY_IMAGE_EXIF_EXPOSUREBIASVALUE		"image.exif.ExposureBiasValue"
#define PROPERTY_IMAGE_EXIF_MAXAPERTUREVALUE		"image.exif.MaxApertureValue"
#define PROPERTY_IMAGE_EXIF_SUBJECTDISTANCE		"image.exif.SubjectDistance"
#define PROPERTY_IMAGE_EXIF_METERINGMODE		"image.exif.MeteringMode"
#define PROPERTY_IMAGE_EXIF_LIGHTSOURCE			"image.exif.LightSource"
#define PROPERTY_IMAGE_EXIF_FLASH			"image.exif.Flash"
#define PROPERTY_IMAGE_EXIF_FOCALLENGTH			"image.exif.FocalLength"
#define PROPERTY_IMAGE_EXIF_FLASHENERGY			"image.exif.FlashEnergy"
#define PROPERTY_IMAGE_EXIF_SPATIALFREQUENCYRESPONSE	"image.exif.SpatialFrequencyResponse"
#define PROPERTY_IMAGE_EXIF_NOISE			"image.exif.Noise"
#define PROPERTY_IMAGE_EXIF_IMAGENUMBER			"image.exif.ImageNumber"
#define PROPERTY_IMAGE_EXIF_SECURITYCLASSIFICATION	"image.exif.SecurityClassification"
#define PROPERTY_IMAGE_EXIF_IMAGEHISTORY		"image.exif.ImageHistory"
#define PROPERTY_IMAGE_EXIF_SUBJECTAREA			"image.exif.SubjectArea"
#define PROPERTY_IMAGE_EXIF_EXPOSUREINDEX		"image.exif.ExposureIndex"
#define PROPERTY_IMAGE_EXIF_TIFFEPSTANDARDID		"image.exif.TIFF/EPStandardID"
#define PROPERTY_IMAGE_EXIF_MAKERNOTE			"image.exif.MakerNote"
#define PROPERTY_IMAGE_EXIF_WINXP_TITLE			"image.exif.WinXP-Title"
#define PROPERTY_IMAGE_EXIF_WINXP_COMMENTS		"image.exif.WinXP-Comments"
#define PROPERTY_IMAGE_EXIF_WINXP_AUTHOR		"image.exif.WinXP-Author"
#define PROPERTY_IMAGE_EXIF_WINXP_KEYWORDS		"image.exif.WinXP-Keywords"
#define PROPERTY_IMAGE_EXIF_WINXP_SUBJECT		"image.exif.WinXP-Subject"
#define PROPERTY_IMAGE_EXIF_USERCOMMENT			"image.exif.UserComment"
#define PROPERTY_IMAGE_EXIF_SUBSECTIME			"image.exif.SubSecTime"
#define PROPERTY_IMAGE_EXIF_SUBSECTIMEORIGINAL		"image.exif.SubSecTimeOriginal"
#define PROPERTY_IMAGE_EXIF_SUBSECTIMEDIGITIZED		"image.exif.SubSecTimeDigitized"
#define PROPERTY_IMAGE_EXIF_FLASHPIXVERSION		"image.exif.FlashPixVersion"
#define PROPERTY_IMAGE_EXIF_COLORSPACE			"image.exif.ColorSpace"
#define PROPERTY_IMAGE_EXIF_EXIFIMAGEWIDTH		"image.exif.ExifImageWidth"
#define PROPERTY_IMAGE_EXIF_EXIFIMAGELENGTH		"image.exif.ExifImageLength"
#define PROPERTY_IMAGE_EXIF_RELATEDSOUNDFILE		"image.exif.RelatedSoundFile"
#define PROPERTY_IMAGE_EXIF_INTEROPERABILITYOFFSET	"image.exif.InteroperabilityOffset"
#define PROPERTY_IMAGE_EXIF_FLASHENERGY			"image.exif.FlashEnergy"
#define PROPERTY_IMAGE_EXIF_SPATIALFREQUENCYRESPONSE	"image.exif.SpatialFrequencyResponse"
#define PROPERTY_IMAGE_EXIF_NOISE			"image.exif.Noise"
#define PROPERTY_IMAGE_EXIF_FOCALPLANEXRESOLUTION	"image.exif.FocalPlaneXResolution"
#define PROPERTY_IMAGE_EXIF_FOCALPLANEYRESOLUTION	"image.exif.FocalPlaneYResolution"
#define PROPERTY_IMAGE_EXIF_FOCALPLANERESOLUTIONUNIT	"image.exif.FocalPlaneResolutionUnit"
#define PROPERTY_IMAGE_EXIF_SUBJECTLOCATION		"image.exif.SubjectLocation"
#define PROPERTY_IMAGE_EXIF_EXPOSUREINDEX		"image.exif.ExposureIndex"
#define PROPERTY_IMAGE_EXIF_TIFFEPSTANDARDID		"image.exif.TIFF/EPStandardID"
#define PROPERTY_IMAGE_EXIF_SENSINGMETHOD		"image.exif.SensingMethod"
#define PROPERTY_IMAGE_EXIF_FILESOURCE			"image.exif.FileSource"
#define PROPERTY_IMAGE_EXIF_SCENETYPE			"image.exif.SceneType"
#define PROPERTY_IMAGE_EXIF_CFAPATTERN			"image.exif.CFAPattern"
#define PROPERTY_IMAGE_EXIF_CUSTOMRENDERED		"image.exif.CustomRendered"
#define PROPERTY_IMAGE_EXIF_EXPOSUREMODE		"image.exif.ExposureMode"
#define PROPERTY_IMAGE_EXIF_WHITEBALANCE		"image.exif.WhiteBalance"
#define PROPERTY_IMAGE_EXIF_DIGITALZOOMRATIO		"image.exif.DigitalZoomRatio"
#define PROPERTY_IMAGE_EXIF_FOCALLENGTHIN35MMFILM	"image.exif.FocalLengthIn35mmFilm"
#define PROPERTY_IMAGE_EXIF_SCENECAPTURETYPE		"image.exif.SceneCaptureType"
#define PROPERTY_IMAGE_EXIF_GAINCONTROL			"image.exif.GainControl"
#define PROPERTY_IMAGE_EXIF_CONTRAST			"image.exif.Contrast"
#define PROPERTY_IMAGE_EXIF_SATURATION			"image.exif.Saturation"
#define PROPERTY_IMAGE_EXIF_SHARPNESS			"image.exif.Sharpness"
#define PROPERTY_IMAGE_EXIF_DEVICESETTINGDESCRIPTION	"image.exif.DeviceSettingDescription"
#define PROPERTY_IMAGE_EXIF_SUBJECTDISTANCERANGE	"image.exif.SubjectDistanceRange"
#define PROPERTY_IMAGE_EXIF_IMAGEUNIQUEID		"image.exif.ImageUniqueID"
#define PROPERTY_IMAGE_EXIF_PRINTIMAGEMATCHING		"image.exif.PrintImageMatching"

#endif	/* IMAGEMS_H */
