#!/bin/sh
#
# Uninstall Postgres used by iRODS.
#
# Usage is:
#	./uninstallPostgres [options]
#
# This script uninstalls Postgres, as previously installed
# for iRODS by 'installPostgres'.
#
runfile="uninstallPostgres.pl"



for dir in "./scripts" "." "../scripts" "../../scripts"; do
	if [ -d $dir -a -f $dir/runperl -a -f $dir/perl/$runfile ]; then
		$dir/runperl --script $dir/perl/$runfile $*
		ExitCode="$?"
		exit $ExitCode
	fi
done

echo "Usage error:"
echo "    Please run this script from the top-level directory"
echo "    of the iRODS distribution."
exit 1
