name: build-irods-centos
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:7']
    steps:
      - name: Install git > v2.18 for Checkout
        run:  |
              yum install -y git
              yum install -y \
                https://repo.ius.io/ius-release-el7.rpm \
                https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
              yum swap -y git git224-core
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Prerequisites
        run:  |
              yum -y update ca-certificates
              yum install -y sudo bind-utils wget
              yum -y install gcc g++ libstdc++-static make rpm-build bzip2-devel curl-devel fakeroot help2man openssl-devel pam-devel python-devel unixODBC unixODBC-devel zlib-devel python36-distro
      - name: Get Public IP
        run:  |
              dig +short myip.opendns.com @resolver1.opendns.com
      - name: Install iRODS Externals
        run:  |
              sudo rpm --import https://unstable.irods.org/irods-unstable-signing-key.asc
              wget -qO - https://unstable.irods.org/renci-irods-unstable.yum.repo | sudo tee /etc/yum.repos.d/renci-irods-unstable.yum.repo
              sudo yum -y update
              sudo yum -y install \
                irods-externals-avro1.11.0-0 \
                irods-externals-boost1.78.0-0 \
                irods-externals-catch22.13.8-0 \
                irods-externals-clang-runtime13.0.0-0 \
                irods-externals-clang13.0.0-0 \
                irods-externals-cmake3.21.4-0 \
                irods-externals-cppzmq4.8.1-1 \
                irods-externals-fmt8.0.1-0 \
                irods-externals-json3.10.4-0 \
                irods-externals-libarchive3.5.2-0 \
                irods-externals-nanodbc2.13.0-1 \
                irods-externals-spdlog1.9.2-1 \
                irods-externals-zeromq4-14.1.8-0
      - name: Configure CMake
        run:  |
              export PATH=/opt/irods-externals/cmake3.21.4-0/bin:$PATH
              mkdir build
              cd build
              cmake -DIRODS_DISABLE_COMPILER_OPTIMIZATIONS=ON ../
      - name: Build and Package
        run:  |
              cd build
              make package
