name: build-irods-enterprise-linux-8
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['almalinux:8','rockylinux:8']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run:  |
              dnf -y update ca-certificates
              dnf -y install bind-utils wget git epel-release
              dnf -y install dnf-plugin-config-manager dnf-plugins-core
              dnf config-manager --set-enabled powertools
              dnf -y install gcc gcc-c++ make rpm-build bzip2-devel curl-devel fakeroot openssl-devel pam-devel python36-devel unixODBC unixODBC-devel zlib-devel python3-distro flex bison
      - name: Install iRODS Externals
        run:  |
              rpm --import https://unstable.irods.org/irods-unstable-signing-key.asc
              wget -qO - https://unstable.irods.org/renci-irods-unstable.yum.repo | tee /etc/yum.repos.d/renci-irods-unstable.yum.repo
              sed -i 's/centos/el/' /etc/yum.repos.d/renci-irods-unstable.yum.repo
              dnf -y update
              dnf -y install \
                irods-externals-avro-libcxx1.11.0-3 \
                irods-externals-boost-libcxx1.81.0-1 \
                irods-externals-catch22.13.8-0 \
                irods-externals-clang-runtime13.0.1-0 \
                irods-externals-clang13.0.1-0 \
                irods-externals-cmake3.21.4-0 \
                irods-externals-cppzmq4.8.1-1 \
                irods-externals-fmt-libcxx8.1.1-1 \
                irods-externals-json3.10.4-0 \
                irods-externals-libarchive3.5.2-0 \
                irods-externals-nanodbc-libcxx2.13.0-2 \
                irods-externals-spdlog-libcxx1.9.2-2 \
                irods-externals-zeromq4-1-libcxx4.1.8-1
      - name: Configure CMake
        run:  |
              export PATH=/opt/irods-externals/cmake3.21.4-0/bin:$PATH
              mkdir build
              cd build
              cmake -DIRODS_DISABLE_COMPILER_OPTIMIZATIONS=ON ../
      - name: Build and Package
        run:  |
              cd build
              make package
