name: build-irods-centos
on: [push, pull_request]
env:
  # We need GH actions to use an older version of node for EL7.
  # See: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
jobs:
  build:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:7']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run:  |
              sed -i \
                -e 's/mirror.centos.org/vault.centos.org/g' \
                -e 's/^#.*baseurl=http/baseurl=http/g' \
                -e 's/^mirrorlist=http/#mirrorlist=http/g' \
                /etc/yum.repos.d/*.repo
              yum -y update ca-certificates
              yum -y install bind-utils wget epel-release centos-release-scl
              sed -i \
                -e 's/mirror.centos.org/vault.centos.org/g' \
                -e 's/^#.*baseurl=http/baseurl=http/g' \
                -e 's/^mirrorlist=http/#mirrorlist=http/g' \
                /etc/yum.repos.d/*.repo
              yum -y install gcc g++ libstdc++-static make rpm-build bzip2-devel curl-devel fakeroot openssl-devel pam-devel python-devel unixODBC unixODBC-devel zlib-devel python36-distro
      - name: Install Flex and Bison
        run:  |
              rpm --import https://www.cert.org/forensics/repository/forensics-expires-2022-04-03.asc
              yum -y install https://forensics.cert.org/cert-forensics-tools-release-el7.rpm
              yum -y install flex bison
      - name: Install iRODS Externals
        run:  |
              rpm --import https://unstable.irods.org/irods-unstable-signing-key.asc
              wget -qO - https://unstable.irods.org/renci-irods-unstable.yum.repo | tee /etc/yum.repos.d/renci-irods-unstable.yum.repo
              yum -y update
              yum -y install \
                irods-externals-avro1.11.0-3 \
                irods-externals-boost1.81.0-1 \
                irods-externals-catch22.13.8-0 \
                irods-externals-clang13.0.1-0 \
                irods-externals-cmake3.21.4-0 \
                irods-externals-cppzmq4.8.1-1 \
                irods-externals-fmt8.1.1-1 \
                irods-externals-json3.10.4-0 \
                irods-externals-libarchive3.5.2-0 \
                irods-externals-nanodbc2.13.0-2 \
                irods-externals-spdlog1.9.2-2 \
                irods-externals-zeromq4-14.1.8-1
      - name: Configure CMake
        run:  |
              export PATH=/opt/irods-externals/cmake3.21.4-0/bin:$PATH
              mkdir build
              cd build
              cmake -DIRODS_DISABLE_COMPILER_OPTIMIZATIONS=ON ../
      - name: Build and Package
        run:  |
              cd build
              make package
