name: build-irods-clang-format-linter
on: [push, pull_request]
jobs:
  clang-format-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - name: Install Prerequisites
        run:  |
              apt-get update -qq
              apt-get install -qq apt-transport-https ca-certificates
              apt-get install -qq python3
#     - name: Install libstdc++6
#       run:  |
#             apt-get install -qq software-properties-common
#             add-apt-repository -y ppa:ubuntu-toolchain-r/test
#             apt-get update -qq
#             apt-get install -qq libstdc++6
      - name: Install Clang Compiler
        run:  |
              wget -qO - https://unstable.irods.org/irods-unstable-signing-key.asc | apt-key add -
              echo "deb [arch=amd64] https://unstable.irods.org/apt/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/renci-irods-unstable.list
              apt-get update -qq
              apt-get install -qq irods-externals-clang13.0.0-0
              export PATH=/opt/irods-externals/clang13.0.0-0/bin:$PATH
      - name: Run Clang-Format
        run:  |
              diff_results=$(git clang-format HEAD^ --diff)
              echo CLANG-FORMAT RESULTS = $diff_results
              echo ${{ contains(['no modified files to format\n', 'clang-format did not modify any files\n'], diff_results) }}
